/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vue;

import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author toshiba
 */
public class Dashboard extends javax.swing.JFrame {

    Accueil a = new Accueil();
    Employes e = new Employes();
    Clients cl = new Clients();
    Modeles m = new Modeles();
    Commande cm = new Commande();
    Mesures mr = new Mesures();
    Livraisons l = new Livraisons();
    Factures f = new Factures();
    Magasin mg = new Magasin();
    Profile p = new Profile();
    SeancesE se = new SeancesE();

    String anime = "BIENVENUE DANS LA APPLICATION DE GESTION D'ATELIER DE COUTURE ";

    public Dashboard() {
        initComponents();
        setSize(1000, 600);
        setLocationRelativeTo(this);
        //this.t = jTabbedPane1.getSelectedIndex();

        tabdpan.add(a);
        tabdpan.setSelectedIndex(0);
        AdminUserName();
        lusername.setText(Authentification.adminName());

        Thread th = new Thread(new Runnable() {
            @Override
            public void run() {
                while (true) {
                    char c = anime.charAt(0);
                    String rest = anime.substring(1);
                    anime = rest + c;
                    ltitre.setText(anime);
                    try {
                        Thread.sleep(100);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }

            }
        });
        th.start();
    }

    public void AdminUserName() {
        lusername.setText(Authentification.adminName());
        Profile.tusernamead.setText(Authentification.adminName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pmenu = new javax.swing.JPanel();
        lusername = new javax.swing.JLabel();
        pdecon = new javax.swing.JPanel();
        llogout = new javax.swing.JLabel();
        ldeconnecter = new javax.swing.JLabel();
        pAcc = new javax.swing.JPanel();
        lacc = new javax.swing.JLabel();
        lacc2 = new javax.swing.JLabel();
        pcommandes = new javax.swing.JPanel();
        lCommandes = new javax.swing.JLabel();
        lcommandes = new javax.swing.JLabel();
        pMesures = new javax.swing.JPanel();
        lMesures = new javax.swing.JLabel();
        lmesures = new javax.swing.JLabel();
        pmodeles = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        lmodeles = new javax.swing.JLabel();
        pclients = new javax.swing.JPanel();
        lClients = new javax.swing.JLabel();
        lclients = new javax.swing.JLabel();
        plivraisons = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        llivraisons = new javax.swing.JLabel();
        llivraison = new javax.swing.JLabel();
        pstatistiques = new javax.swing.JPanel();
        lStatistiques = new javax.swing.JLabel();
        lstat = new javax.swing.JLabel();
        pfacteures = new javax.swing.JPanel();
        lfacteures = new javax.swing.JLabel();
        lfact = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        pemployes1 = new javax.swing.JPanel();
        lemployes1 = new javax.swing.JLabel();
        LEMPLOYES1 = new javax.swing.JLabel();
        pse = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        lsee = new javax.swing.JLabel();
        lse = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        ltitre = new javax.swing.JLabel();
        tabdpan = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pmenu.setBackground(new java.awt.Color(51, 78, 172));
        pmenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lusername.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lusername.setForeground(new java.awt.Color(255, 255, 255));
        lusername.setText("username");
        lusername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lusernameMouseClicked(evt);
            }
        });
        pmenu.add(lusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, -1));

        pdecon.setBackground(new java.awt.Color(51, 78, 172));
        pdecon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pdeconMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pdeconMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pdeconMouseExited(evt);
            }
        });
        pdecon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        llogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ihm/logout-30.png"))); // NOI18N
        llogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                llogoutMouseClicked(evt);
            }
        });
        pdecon.add(llogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 0, -1, -1));

        ldeconnecter.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        ldeconnecter.setForeground(new java.awt.Color(255, 255, 255));
        ldeconnecter.setText("Se deconnecter");
        ldeconnecter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ldeconnecter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ldeconnecterMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ldeconnecterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ldeconnecterMouseExited(evt);
            }
        });
        pdecon.add(ldeconnecter, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        pmenu.add(pdecon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, 230, 40));

        pAcc.setBackground(new java.awt.Color(51, 78, 172));
        pAcc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pAccMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pAccMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pAccMouseExited(evt);
            }
        });
        pAcc.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lacc.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lacc.setForeground(new java.awt.Color(255, 255, 255));
        lacc.setText("Accueil");
        lacc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lacc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                laccMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                laccMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                laccMouseExited(evt);
            }
        });
        pAcc.add(lacc, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 11, -1, -1));

        lacc2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ihm/home_3_fill.png"))); // NOI18N
        lacc2.setToolTipText("");
        lacc2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lacc2MouseClicked(evt);
            }
        });
        pAcc.add(lacc2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 40, 40));

        pmenu.add(pAcc, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 230, 40));

        pcommandes.setBackground(new java.awt.Color(51, 78, 172));
        pcommandes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pcommandesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pcommandesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pcommandesMouseExited(evt);
            }
        });
        pcommandes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lCommandes.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lCommandes.setForeground(new java.awt.Color(255, 255, 255));
        lCommandes.setText("Commandes");
        lCommandes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lCommandes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lCommandesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lCommandesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lCommandesMouseExited(evt);
            }
        });
        pcommandes.add(lCommandes, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 16, -1, -1));

        lcommandes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ihm/shopping_bag_1_fill.png"))); // NOI18N
        lcommandes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lcommandesMouseClicked(evt);
            }
        });
        pcommandes.add(lcommandes, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 30, 40));

        pmenu.add(pcommandes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 230, 40));

        pMesures.setBackground(new java.awt.Color(51, 78, 172));
        pMesures.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pMesuresMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pMesuresMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pMesuresMouseExited(evt);
            }
        });
        pMesures.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lMesures.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lMesures.setForeground(new java.awt.Color(255, 255, 255));
        lMesures.setText("Mesures");
        lMesures.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lMesures.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lMesuresMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lMesuresMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lMesuresMouseExited(evt);
            }
        });
        pMesures.add(lMesures, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 11, -1, -1));

        lmesures.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ihm/pencil_ruler_fill.png"))); // NOI18N
        lmesures.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lmesuresMouseClicked(evt);
            }
        });
        pMesures.add(lmesures, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 30, 40));

        pmenu.add(pMesures, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 230, 40));

        pmodeles.setBackground(new java.awt.Color(51, 78, 172));
        pmodeles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pmodelesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pmodelesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pmodelesMouseExited(evt);
            }
        });
        pmodeles.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Models");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel8MouseExited(evt);
            }
        });
        pmodeles.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 11, -1, -1));

        lmodeles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ihm/skirt_fill.png"))); // NOI18N
        lmodeles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lmodelesMouseClicked(evt);
            }
        });
        pmodeles.add(lmodeles, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 30, 40));

        pmenu.add(pmodeles, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 230, 40));

        pclients.setBackground(new java.awt.Color(51, 78, 172));
        pclients.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pclientsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pclientsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pclientsMouseExited(evt);
            }
        });
        pclients.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lClients.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lClients.setForeground(new java.awt.Color(255, 255, 255));
        lClients.setText("Clients");
        lClients.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lClients.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lClientsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lClientsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lClientsMouseExited(evt);
            }
        });
        pclients.add(lClients, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 11, -1, -1));

        lclients.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ihm/group_2_line.png"))); // NOI18N
        lclients.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lclientsMouseClicked(evt);
            }
        });
        pclients.add(lclients, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 30, 40));

        pmenu.add(pclients, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 230, 40));

        plivraisons.setBackground(new java.awt.Color(51, 78, 172));
        plivraisons.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                plivraisonsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                plivraisonsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                plivraisonsMouseExited(evt);
            }
        });
        plivraisons.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        plivraisons.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 180, 50));

        llivraisons.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        llivraisons.setForeground(new java.awt.Color(255, 255, 255));
        llivraisons.setText("livraisons");
        llivraisons.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                llivraisonsMouseClicked(evt);
            }
        });
        plivraisons.add(llivraisons, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        llivraison.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ihm/truck_fill.png"))); // NOI18N
        llivraison.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                llivraisonMouseClicked(evt);
            }
        });
        plivraisons.add(llivraison, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 30, 40));

        pmenu.add(plivraisons, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 230, 40));

        pstatistiques.setBackground(new java.awt.Color(51, 78, 172));
        pstatistiques.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pstatistiquesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pstatistiquesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pstatistiquesMouseExited(evt);
            }
        });
        pstatistiques.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lStatistiques.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lStatistiques.setForeground(new java.awt.Color(255, 255, 255));
        lStatistiques.setText("Magasins");
        pstatistiques.add(lStatistiques, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        lstat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ihm/shop_fill.png"))); // NOI18N
        pstatistiques.add(lstat, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 30, 40));

        pmenu.add(pstatistiques, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 230, 40));

        pfacteures.setBackground(new java.awt.Color(51, 78, 172));
        pfacteures.setForeground(new java.awt.Color(255, 255, 255));
        pfacteures.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pfacteuresMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pfacteuresMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pfacteuresMouseExited(evt);
            }
        });
        pfacteures.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lfacteures.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lfacteures.setForeground(new java.awt.Color(255, 255, 255));
        lfacteures.setText("Facteures");
        lfacteures.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lfacteuresMouseClicked(evt);
            }
        });
        pfacteures.add(lfacteures, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 15, -1, -1));

        lfact.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ihm/inventory_fill.png"))); // NOI18N
        lfact.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lfactMouseClicked(evt);
            }
        });
        pfacteures.add(lfact, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 30, 40));

        pmenu.add(pfacteures, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 230, 40));
        pmenu.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 190, 10));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ihm/scissors_2_line.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        pmenu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 60, 60));

        pemployes1.setBackground(new java.awt.Color(51, 78, 172));
        pemployes1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pemployes1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pemployes1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pemployes1MouseExited(evt);
            }
        });
        pemployes1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pemployes1FocusGained(evt);
            }
        });
        pemployes1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lemployes1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lemployes1.setForeground(new java.awt.Color(255, 255, 255));
        lemployes1.setText("Employes");
        lemployes1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lemployes1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lemployes1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lemployes1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lemployes1MouseExited(evt);
            }
        });
        pemployes1.add(lemployes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 11, -1, -1));

        LEMPLOYES1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ihm/group_3_fill (2).png"))); // NOI18N
        LEMPLOYES1.setToolTipText("");
        LEMPLOYES1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LEMPLOYES1MouseClicked(evt);
            }
        });
        pemployes1.add(LEMPLOYES1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 40, 40));

        pmenu.add(pemployes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 230, 40));

        pse.setBackground(new java.awt.Color(51, 78, 172));
        pse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pseMouseExited(evt);
            }
        });
        pse.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pse.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 180, 50));

        lsee.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lsee.setForeground(new java.awt.Color(255, 255, 255));
        lsee.setText("Séances d'essayage ");
        lsee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lseeMouseClicked(evt);
            }
        });
        pse.add(lsee, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        lse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ihm/skirt_fill.png"))); // NOI18N
        lse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lseMouseClicked(evt);
            }
        });
        pse.add(lse, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 30, 40));

        pmenu.add(pse, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 230, 40));

        getContentPane().add(pmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 700));

        jPanel7.setBackground(new java.awt.Color(112, 150, 209));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ltitre.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        ltitre.setForeground(new java.awt.Color(255, 255, 255));
        jPanel7.add(ltitre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 670, 20));

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 770, 70));

        tabdpan.setBackground(new java.awt.Color(255, 255, 0));
        getContentPane().add(tabdpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 780, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pAccMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pAccMouseEntered
        pAcc.setBackground(Color.decode("#7096d1"));
    }//GEN-LAST:event_pAccMouseEntered

    private void laccMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laccMouseExited
        pAcc.setBackground(Color.decode("#334EAC"));
    }//GEN-LAST:event_laccMouseExited

    private void laccMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laccMouseEntered

    }//GEN-LAST:event_laccMouseEntered

    private void lClientsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lClientsMouseEntered
        pclients.setBackground(Color.decode("#7096d1"));
    }//GEN-LAST:event_lClientsMouseEntered

    private void lClientsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lClientsMouseExited
        pclients.setBackground(Color.decode("#334EAC"));
    }//GEN-LAST:event_lClientsMouseExited

    private void lCommandesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lCommandesMouseEntered
        pcommandes.setBackground(Color.decode("#7096d1"));
    }//GEN-LAST:event_lCommandesMouseEntered

    private void lCommandesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lCommandesMouseExited
        pcommandes.setBackground(Color.decode("#334EAC"));
    }//GEN-LAST:event_lCommandesMouseExited

    private void lMesuresMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lMesuresMouseEntered
        pMesures.setBackground(Color.decode("#7096d1"));
    }//GEN-LAST:event_lMesuresMouseEntered

    private void lMesuresMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lMesuresMouseExited
        pMesures.setBackground(Color.decode("#334EAC"));
    }//GEN-LAST:event_lMesuresMouseExited

    private void jLabel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseEntered
        pmodeles.setBackground(Color.decode("#7096d1"));
    }//GEN-LAST:event_jLabel8MouseEntered

    private void jLabel8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseExited
        pmodeles.setBackground(Color.decode("#334EAC"));
    }//GEN-LAST:event_jLabel8MouseExited

    private void ldeconnecterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ldeconnecterMouseEntered
        pdecon.setBackground(Color.decode("#7096d1"));
    }//GEN-LAST:event_ldeconnecterMouseEntered

    private void ldeconnecterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ldeconnecterMouseExited
        pdecon.setBackground(Color.decode("#334EAC"));
    }//GEN-LAST:event_ldeconnecterMouseExited

    private void laccMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laccMouseClicked

        tabdpan.add(a);
        tabdpan.remove(e);
        tabdpan.remove(cl);
        tabdpan.remove(cm);
        tabdpan.remove(m);
        tabdpan.remove(mr);
        tabdpan.remove(l);
        tabdpan.remove(f);
        a.nbModeles();
        a.nbclients();
        a.nbemployes();
        a.nbFactures();
        a.nbLivraisons();
        a.nbCommandes();
        tabdpan.remove(mg);
        tabdpan.remove(p);
        tabdpan.remove(se);
    }//GEN-LAST:event_laccMouseClicked

    private void lClientsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lClientsMouseClicked
        tabdpan.add(cl);
        tabdpan.remove(e);
        tabdpan.remove(a);
        tabdpan.remove(cm);
        tabdpan.remove(m);
        tabdpan.remove(mr);
        tabdpan.remove(l);
        tabdpan.remove(f);
        tabdpan.remove(mg);
        tabdpan.remove(p);
        tabdpan.remove(se);

    }//GEN-LAST:event_lClientsMouseClicked


    private void pAccMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pAccMouseClicked

        tabdpan.add(a);
        tabdpan.remove(e);
        tabdpan.remove(cl);
        tabdpan.remove(cm);
        tabdpan.remove(m);
        tabdpan.remove(mr);
        tabdpan.remove(l);
        tabdpan.remove(f);
        a.nbModeles();
        a.nbclients();
        a.nbemployes();
        a.nbFactures();
        a.nbLivraisons();
        a.nbCommandes();
        tabdpan.remove(mg);
        tabdpan.remove(p);
        tabdpan.remove(se);
    }//GEN-LAST:event_pAccMouseClicked

    private void pdeconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pdeconMouseClicked

    }//GEN-LAST:event_pdeconMouseClicked

    private void pcommandesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pcommandesMouseClicked
        tabdpan.add(cm);
        cm.actualiserPA();
        cm.actualiserSM();
        tabdpan.remove(a);
        tabdpan.remove(cl);
        tabdpan.remove(e);
        tabdpan.remove(m);
        tabdpan.remove(mr);
        tabdpan.remove(l);
        tabdpan.remove(f);
        tabdpan.remove(mg);
        tabdpan.remove(p);
        tabdpan.remove(se);
    }//GEN-LAST:event_pcommandesMouseClicked

    private void pclientsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pclientsMouseClicked
        tabdpan.add(cl);
        tabdpan.remove(e);
        tabdpan.remove(a);
        tabdpan.remove(cm);
        tabdpan.remove(m);
        tabdpan.remove(mr);
        tabdpan.remove(l);
        tabdpan.remove(f);
        tabdpan.remove(mg);
        tabdpan.remove(p);
        tabdpan.remove(se);
    }//GEN-LAST:event_pclientsMouseClicked

    private void lusernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lusernameMouseClicked
        tabdpan.add(p);
        tabdpan.remove(a);
        tabdpan.remove(e);
        tabdpan.remove(cl);
        tabdpan.remove(cm);
        tabdpan.remove(mr);
        tabdpan.remove(l);
        tabdpan.remove(f);
        tabdpan.remove(mg);
        tabdpan.remove(m);
        tabdpan.remove(se);
    }//GEN-LAST:event_lusernameMouseClicked

    private void pmodelesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pmodelesMouseClicked
        tabdpan.add(m);
        tabdpan.remove(a);
        tabdpan.remove(e);
        tabdpan.remove(cl);
        tabdpan.remove(cm);
        tabdpan.remove(mr);
        tabdpan.remove(l);
        tabdpan.remove(f);
        tabdpan.remove(mg);
        tabdpan.remove(p);
        tabdpan.remove(se);
    }//GEN-LAST:event_pmodelesMouseClicked

    private void lacc2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lacc2MouseClicked

        tabdpan.add(a);
        tabdpan.remove(e);
        tabdpan.remove(cl);
        tabdpan.remove(cm);
        tabdpan.remove(m);
        tabdpan.remove(mr);
        tabdpan.remove(l);
        tabdpan.remove(f);
        a.nbModeles();
        a.nbclients();
        a.nbemployes();
        a.nbFactures();
        a.nbLivraisons();
        a.nbCommandes();
        tabdpan.remove(mg);
        tabdpan.remove(p);
        tabdpan.remove(se);
    }//GEN-LAST:event_lacc2MouseClicked

    private void lclientsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lclientsMouseClicked
        tabdpan.add(cl);
        tabdpan.remove(e);
        tabdpan.remove(a);
        tabdpan.remove(cm);
        tabdpan.remove(m);
        tabdpan.remove(mr);
        tabdpan.remove(l);
        tabdpan.remove(f);
        tabdpan.remove(mg);
        tabdpan.remove(p);
        tabdpan.remove(se);
    }//GEN-LAST:event_lclientsMouseClicked

    private void lcommandesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lcommandesMouseClicked
        tabdpan.add(cm);
        cm.actualiserPA();
        cm.actualiserSM();
        tabdpan.remove(a);
        tabdpan.remove(cl);
        tabdpan.remove(e);
        tabdpan.remove(m);
        tabdpan.remove(mr);
        tabdpan.remove(l);
        tabdpan.remove(f);
        tabdpan.remove(mg);
        tabdpan.remove(p);
        tabdpan.remove(se);
    }//GEN-LAST:event_lcommandesMouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        tabdpan.add(m);
        tabdpan.remove(a);
        tabdpan.remove(e);
        tabdpan.remove(cl);
        tabdpan.remove(cm);
        tabdpan.remove(mr);
        tabdpan.remove(l);
        tabdpan.remove(f);
        tabdpan.remove(mg);
        tabdpan.remove(p);
        tabdpan.remove(se);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void lmodelesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lmodelesMouseClicked
        tabdpan.add(m);
        tabdpan.remove(a);
        tabdpan.remove(e);
        tabdpan.remove(cl);
        tabdpan.remove(cm);
        tabdpan.remove(mr);
        tabdpan.remove(l);
        tabdpan.remove(f);
        tabdpan.remove(mg);
        tabdpan.remove(p);
        tabdpan.remove(se);
    }//GEN-LAST:event_lmodelesMouseClicked

    private void lCommandesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lCommandesMouseClicked
        tabdpan.add(cm);
        cm.actualiserPA();
        cm.actualiserSM();
        tabdpan.remove(a);
        tabdpan.remove(cl);
        tabdpan.remove(e);
        tabdpan.remove(m);
        tabdpan.remove(mr);
        tabdpan.remove(l);
        tabdpan.remove(f);
        tabdpan.remove(mg);
        tabdpan.remove(p);
        tabdpan.remove(se);
    }//GEN-LAST:event_lCommandesMouseClicked

    private void plivraisonsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plivraisonsMouseEntered
        plivraisons.setBackground(Color.decode("#7096d1"));
    }//GEN-LAST:event_plivraisonsMouseEntered

    private void plivraisonsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plivraisonsMouseExited
        plivraisons.setBackground(Color.decode("#334EAC"));
    }//GEN-LAST:event_plivraisonsMouseExited

    private void pAccMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pAccMouseExited
        pAcc.setBackground(Color.decode("#334EAC"));
    }//GEN-LAST:event_pAccMouseExited

    private void pclientsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pclientsMouseExited
        pclients.setBackground(Color.decode("#334EAC"));
    }//GEN-LAST:event_pclientsMouseExited

    private void pcommandesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pcommandesMouseExited
        pcommandes.setBackground(Color.decode("#334EAC"));
    }//GEN-LAST:event_pcommandesMouseExited

    private void pMesuresMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pMesuresMouseExited
        pMesures.setBackground(Color.decode("#334EAC"));
    }//GEN-LAST:event_pMesuresMouseExited

    private void pmodelesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pmodelesMouseExited
        pmodeles.setBackground(Color.decode("#334EAC"));
    }//GEN-LAST:event_pmodelesMouseExited

    private void pfacteuresMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pfacteuresMouseExited
        pfacteures.setBackground(Color.decode("#334EAC"));
    }//GEN-LAST:event_pfacteuresMouseExited

    private void pclientsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pclientsMouseEntered
        pclients.setBackground(Color.decode("#7096d1"));
    }//GEN-LAST:event_pclientsMouseEntered

    private void pcommandesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pcommandesMouseEntered
        pcommandes.setBackground(Color.decode("#7096d1"));
    }//GEN-LAST:event_pcommandesMouseEntered

    private void pMesuresMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pMesuresMouseEntered
        pMesures.setBackground(Color.decode("#7096d1"));
    }//GEN-LAST:event_pMesuresMouseEntered

    private void pmodelesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pmodelesMouseEntered
        pmodeles.setBackground(Color.decode("#7096d1"));
    }//GEN-LAST:event_pmodelesMouseEntered

    private void pfacteuresMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pfacteuresMouseEntered
        pfacteures.setBackground(Color.decode("#7096d1"));
    }//GEN-LAST:event_pfacteuresMouseEntered

    private void pstatistiquesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pstatistiquesMouseEntered
        pstatistiques.setBackground(Color.decode("#7096d1"));
    }//GEN-LAST:event_pstatistiquesMouseEntered

    private void pstatistiquesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pstatistiquesMouseExited
        pstatistiques.setBackground(Color.decode("#334EAC"));
    }//GEN-LAST:event_pstatistiquesMouseExited

    private void pdeconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pdeconMouseEntered
        pdecon.setBackground(Color.decode("#7096d1"));
    }//GEN-LAST:event_pdeconMouseEntered

    private void pdeconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pdeconMouseExited
        pdecon.setBackground(Color.decode("#334EAC"));
    }//GEN-LAST:event_pdeconMouseExited

    private void ldeconnecterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ldeconnecterMouseClicked
        int optclick = JOptionPane.showConfirmDialog(this,
                "voulez vous vraiment quiter ?", "confirmation", JOptionPane.YES_NO_OPTION);

        if (optclick == 0) {
            System.exit(0);

        }
    }//GEN-LAST:event_ldeconnecterMouseClicked

    private void llogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_llogoutMouseClicked
        int optclick = JOptionPane.showConfirmDialog(this,
                "voulez vous vraiment quiter ?", "confirmation", JOptionPane.YES_NO_OPTION);
        if (optclick == 0) {
            System.exit(0);

        }
    }//GEN-LAST:event_llogoutMouseClicked

    private void lMesuresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lMesuresMouseClicked
        tabdpan.add(mr);
        tabdpan.remove(a);
        tabdpan.remove(cl);
        tabdpan.remove(e);
        tabdpan.remove(m);
        tabdpan.remove(cm);
        tabdpan.remove(l);
        tabdpan.remove(f);
        tabdpan.remove(mg);
        mr.actualiser();
        tabdpan.remove(p);
        tabdpan.remove(se);

    }//GEN-LAST:event_lMesuresMouseClicked

    private void plivraisonsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plivraisonsMouseClicked
        tabdpan.add(l);
        tabdpan.remove(a);
        tabdpan.remove(cl);
        tabdpan.remove(e);
        tabdpan.remove(m);
        tabdpan.remove(cm);
        tabdpan.remove(mr);
        tabdpan.remove(f);
        tabdpan.remove(mg);
        l.actualiser();
        tabdpan.remove(p);
        tabdpan.remove(se);

    }//GEN-LAST:event_plivraisonsMouseClicked

    private void llivraisonsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_llivraisonsMouseClicked
        tabdpan.add(l);
        tabdpan.remove(a);
        tabdpan.remove(cl);
        tabdpan.remove(e);
        tabdpan.remove(m);
        tabdpan.remove(cm);
        tabdpan.remove(mr);
        tabdpan.remove(f);
        tabdpan.remove(mg);
        l.actualiser();
        tabdpan.remove(p);
        tabdpan.remove(se);

    }//GEN-LAST:event_llivraisonsMouseClicked

    private void lfacteuresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lfacteuresMouseClicked
        tabdpan.add(f);
        tabdpan.remove(a);
        tabdpan.remove(cl);
        tabdpan.remove(e);
        tabdpan.remove(m);
        tabdpan.remove(cm);
        tabdpan.remove(mr);
        tabdpan.remove(l);
        tabdpan.remove(mg);
        f.actualiser();
        tabdpan.remove(p);
        tabdpan.remove(se);

    }//GEN-LAST:event_lfacteuresMouseClicked

    private void pstatistiquesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pstatistiquesMouseClicked
        tabdpan.add(mg);
        tabdpan.remove(a);
        tabdpan.remove(cl);
        tabdpan.remove(e);
        tabdpan.remove(m);
        tabdpan.remove(cm);
        tabdpan.remove(mr);
        tabdpan.remove(l);
        tabdpan.remove(f);
        tabdpan.remove(p);
         tabdpan.remove(se);
    }//GEN-LAST:event_pstatistiquesMouseClicked

    private void llivraisonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_llivraisonMouseClicked
        tabdpan.add(l);
        tabdpan.remove(a);
        tabdpan.remove(cl);
        tabdpan.remove(e);
        tabdpan.remove(m);
        tabdpan.remove(cm);
        tabdpan.remove(mr);
        tabdpan.remove(f);
        tabdpan.remove(mg);
        l.actualiser();
        tabdpan.remove(p);
         tabdpan.remove(se);
    }//GEN-LAST:event_llivraisonMouseClicked

    private void lfactMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lfactMouseClicked
        tabdpan.add(f);
        tabdpan.remove(a);
        tabdpan.remove(cl);
        tabdpan.remove(e);
        tabdpan.remove(m);
        tabdpan.remove(cm);
        tabdpan.remove(mr);
        tabdpan.remove(l);
        tabdpan.remove(mg);
        f.actualiser();
        tabdpan.remove(p);
         tabdpan.remove(se);
    }//GEN-LAST:event_lfactMouseClicked

    private void pfacteuresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pfacteuresMouseClicked
        tabdpan.add(f);
        tabdpan.remove(a);
        tabdpan.remove(cl);
        tabdpan.remove(e);
        tabdpan.remove(m);
        tabdpan.remove(cm);
        tabdpan.remove(mr);
        tabdpan.remove(l);
        tabdpan.remove(mg);
        f.actualiser();
        tabdpan.remove(p);
         tabdpan.remove(se);
    }//GEN-LAST:event_pfacteuresMouseClicked

    private void lemployes1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lemployes1MouseClicked
        tabdpan.add(e);
        tabdpan.remove(a);
        tabdpan.remove(cl);
        tabdpan.remove(f);
        tabdpan.remove(m);
        tabdpan.remove(cm);
        tabdpan.remove(mr);
        tabdpan.remove(l);
        tabdpan.remove(mg);
        tabdpan.remove(p);
         tabdpan.remove(se);
    }//GEN-LAST:event_lemployes1MouseClicked

    private void lemployes1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lemployes1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lemployes1MouseEntered

    private void lemployes1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lemployes1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lemployes1MouseExited

    private void LEMPLOYES1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LEMPLOYES1MouseClicked
        tabdpan.add(e);
        tabdpan.remove(a);
        tabdpan.remove(cl);
        tabdpan.remove(f);
        tabdpan.remove(m);
        tabdpan.remove(cm);
        tabdpan.remove(mr);
        tabdpan.remove(l);
        tabdpan.remove(mg);
        tabdpan.remove(p);
         tabdpan.remove(se);
    }//GEN-LAST:event_LEMPLOYES1MouseClicked

    private void pemployes1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pemployes1MouseClicked
        tabdpan.add(e);
        tabdpan.remove(a);
        tabdpan.remove(cl);
        tabdpan.remove(f);
        tabdpan.remove(m);
        tabdpan.remove(cm);
        tabdpan.remove(mr);
        tabdpan.remove(l);
        tabdpan.remove(mg);
        tabdpan.remove(p);
         tabdpan.remove(se);
    }//GEN-LAST:event_pemployes1MouseClicked

    private void pemployes1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pemployes1MouseEntered
        pemployes1.setBackground(Color.decode("#7096d1"));
    }//GEN-LAST:event_pemployes1MouseEntered

    private void pemployes1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pemployes1MouseExited
        pemployes1.setBackground(Color.decode("#334EAC"));
    }//GEN-LAST:event_pemployes1MouseExited

    private void pemployes1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pemployes1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_pemployes1FocusGained

    private void pMesuresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pMesuresMouseClicked
        tabdpan.add(mr);
        tabdpan.remove(a);
        tabdpan.remove(cl);
        tabdpan.remove(e);
        tabdpan.remove(m);
        tabdpan.remove(cm);
        tabdpan.remove(l);
        tabdpan.remove(f);
        tabdpan.remove(mg);
        mr.actualiser();
        tabdpan.remove(p);
         tabdpan.remove(se);
    }//GEN-LAST:event_pMesuresMouseClicked

    private void lmesuresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lmesuresMouseClicked
        tabdpan.add(mr);
        tabdpan.remove(a);
        tabdpan.remove(cl);
        tabdpan.remove(e);
        tabdpan.remove(m);
        tabdpan.remove(cm);
        tabdpan.remove(l);
        tabdpan.remove(f);
        tabdpan.remove(mg);
        mr.actualiser();
        tabdpan.remove(p);
         tabdpan.remove(se);
    }//GEN-LAST:event_lmesuresMouseClicked

    private void lseeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lseeMouseClicked
        tabdpan.add(se);
        tabdpan.remove(a);
        tabdpan.remove(cl);
        tabdpan.remove(e);
        tabdpan.remove(m);
        tabdpan.remove(cm);
        tabdpan.remove(l);
        tabdpan.remove(f);
        tabdpan.remove(mg);
        tabdpan.remove(p);
        tabdpan.remove(mr);
    }//GEN-LAST:event_lseeMouseClicked

    private void lseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lseMouseClicked
        tabdpan.add(se);
        tabdpan.remove(a);
        tabdpan.remove(cl);
        tabdpan.remove(e);
        tabdpan.remove(m);
        tabdpan.remove(cm);
        tabdpan.remove(l);
        tabdpan.remove(f);
        tabdpan.remove(mg);
        tabdpan.remove(p);
        tabdpan.remove(mr);
    }//GEN-LAST:event_lseMouseClicked

    private void pseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pseMouseClicked
        tabdpan.add(se);
        tabdpan.remove(a);
        tabdpan.remove(cl);
        tabdpan.remove(e);
        tabdpan.remove(m);
        tabdpan.remove(cm);
        tabdpan.remove(l);
        tabdpan.remove(f);
        tabdpan.remove(mg);
        tabdpan.remove(p);
        tabdpan.remove(mr);
    }//GEN-LAST:event_pseMouseClicked

    private void pseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pseMouseEntered
        pse.setBackground(Color.decode("#7096d1"));
    }//GEN-LAST:event_pseMouseEntered

    private void pseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pseMouseExited
        pse.setBackground(Color.decode("#334EAC"));
    }//GEN-LAST:event_pseMouseExited

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        tabdpan.add(a);
        tabdpan.remove(e);
        tabdpan.remove(cl);
        tabdpan.remove(cm);
        tabdpan.remove(m);
        tabdpan.remove(mr);
        tabdpan.remove(l);
        tabdpan.remove(f);
        a.nbModeles();
        a.nbclients();
        a.nbemployes();
        a.nbFactures();
        a.nbLivraisons();
        a.nbCommandes();
        tabdpan.remove(mg);
        tabdpan.remove(p);
        tabdpan.remove(se);
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LEMPLOYES1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lClients;
    private javax.swing.JLabel lCommandes;
    private javax.swing.JLabel lMesures;
    private javax.swing.JLabel lStatistiques;
    private javax.swing.JLabel lacc;
    private javax.swing.JLabel lacc2;
    private javax.swing.JLabel lclients;
    private javax.swing.JLabel lcommandes;
    private javax.swing.JLabel ldeconnecter;
    private javax.swing.JLabel lemployes1;
    private javax.swing.JLabel lfact;
    private javax.swing.JLabel lfacteures;
    private javax.swing.JLabel llivraison;
    private javax.swing.JLabel llivraisons;
    private javax.swing.JLabel llogout;
    private javax.swing.JLabel lmesures;
    private javax.swing.JLabel lmodeles;
    private javax.swing.JLabel lse;
    private javax.swing.JLabel lsee;
    private javax.swing.JLabel lstat;
    private javax.swing.JLabel ltitre;
    public static javax.swing.JLabel lusername;
    private javax.swing.JPanel pAcc;
    private javax.swing.JPanel pMesures;
    private javax.swing.JPanel pclients;
    private javax.swing.JPanel pcommandes;
    private javax.swing.JPanel pdecon;
    private javax.swing.JPanel pemployes1;
    private javax.swing.JPanel pfacteures;
    private javax.swing.JPanel plivraisons;
    private javax.swing.JPanel pmenu;
    private javax.swing.JPanel pmodeles;
    private javax.swing.JPanel pse;
    private javax.swing.JPanel pstatistiques;
    public static javax.swing.JTabbedPane tabdpan;
    // End of variables declaration//GEN-END:variables
}
