/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vue;

/**
 *
 * @author toshiba
 */
public class FicheF extends javax.swing.JFrame {

    /**
     * Creates new form FicheF
     */
    public FicheF() {
        initComponents();
        setLocationRelativeTo(this);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ficheFacture = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ladresseM = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        ldatefact = new javax.swing.JLabel();
        prixmodele = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lnumfact = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        ltotal = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        nomA = new javax.swing.JLabel();
        lnomM = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nommodele = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        ladresseA = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ficheFacture.setBackground(new java.awt.Color(255, 255, 255));
        ficheFacture.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ihm/1713451988270.png"))); // NOI18N
        ficheFacture.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, -10, 150, 100));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 78, 172));
        jLabel4.setText("Facture");
        ficheFacture.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 90, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Vendeur");
        ficheFacture.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Client ");
        ficheFacture.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        ladresseM.setText("......................................");
        ficheFacture.add(ladresseM, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("Date de facturation");
        ficheFacture.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("Numero de facture");
        ficheFacture.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, -1, -1));

        ldatefact.setText("................");
        ficheFacture.add(ldatefact, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        prixmodele.setText(".............");
        ficheFacture.add(prixmodele, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setText("Modele");
        ficheFacture.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, -1, -1));

        lnumfact.setText(".............");
        ficheFacture.add(lnumfact, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20.setText("Total a payer");
        ficheFacture.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        ltotal.setText(".............");
        ficheFacture.add(ltotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, -1, -1));

        jLabel22.setText("DA");
        ficheFacture.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, -1, 20));

        nomA.setText("..............");
        ficheFacture.add(nomA, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, -1, -1));

        lnomM.setText(".....................");
        ficheFacture.add(lnomM, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 60, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ihm/close_fill.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        ficheFacture.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        nommodele.setText(".............");
        ficheFacture.add(nommodele, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, -1, -1));

        jLabel24.setText("DA");
        ficheFacture.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, -1, 20));
        ficheFacture.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 350, 10));
        ficheFacture.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 350, 20));

        ladresseA.setText("......................................");
        ficheFacture.add(ladresseA, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));

        getContentPane().add(ficheFacture, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel7MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FicheF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FicheF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FicheF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FicheF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FicheF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ficheFacture;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    public static javax.swing.JLabel ladresseA;
    public javax.swing.JLabel ladresseM;
    public javax.swing.JLabel ldatefact;
    public javax.swing.JLabel lnomM;
    public javax.swing.JLabel lnumfact;
    public javax.swing.JLabel ltotal;
    public static javax.swing.JLabel nomA;
    public javax.swing.JLabel nommodele;
    public javax.swing.JLabel prixmodele;
    // End of variables declaration//GEN-END:variables
}
