/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vue;

import Model.*;
import Beans.Variante;
import java.awt.HeadlessException;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author toshiba
 */
public class ListeDesVariantes extends javax.swing.JFrame {

    /**
     * Creates new form ListeDesStagiaires
     */
    ConnectVariante cv = new ConnectVariante();
    Statement stat;
    Connexion co = new Connexion();
    PreparedStatement ps;

    public ListeDesVariantes(JPanel jPanel1, JScrollPane jScrollPane1, JTable jTable1) throws HeadlessException {

        this.jPanel1 = jPanel1;
        this.jScrollPane1 = jScrollPane1;
        this.tabVariante = jTable1;
    }
    ConnectClients cc = new ConnectClients();
    DefaultTableModel dtm = new DefaultTableModel();

    public ListeDesVariantes() {
        initComponents();
        setLocationRelativeTo(this);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        actualiser();
        pajoutervr.setVisible(false);
        bmodifier.setVisible(false);
        bsupp.setVisible(false);
        reinitialiser();

    }

    public void afficher(int nligne) {
        Modeles.tidvar.setText(tabVariante.getValueAt(nligne, 0).toString());
        Modeles.tnomvar.setText(tabVariante.getValueAt(nligne, 1).toString());
        Modeles.tstylevar.setText(tabVariante.getValueAt(nligne, 2).toString());

    }

    public void actualiser() {
        //vider la table
        dtm.setColumnCount(0);
        dtm.setRowCount(0);
        try {
            cv.ps = cv.co.getCo().prepareStatement("SELECT* FROM variantes");
            cv.rs = cv.ps.executeQuery();
        } catch (SQLException ex) {
            Logger.getLogger(ListeDesVariantes.class.getName()).log(Level.SEVERE, null, ex);
        }

        dtm.addColumn("id");
        dtm.addColumn("nom");
        dtm.addColumn("style");

        try {
            while (cv.rs.next()) {
                dtm.addRow(new Object[]{
                    cv.rs.getInt("id"), cv.rs.getString("nom"), cv.rs.getString("style")
                });
            }
            tabVariante.setModel(dtm);
        } catch (SQLException ex) {
            Logger.getLogger(ListeDesVariantes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public static void reinitialiser() {
        tnomvar1.setText(null);
        tstyle1.setText(null);
        bmodify.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pajoutervr = new javax.swing.JPanel();
        tnomvar1 = new javax.swing.JTextField();
        tstyle1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        bajoute = new javax.swing.JButton();
        bmodify = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabVariante = new javax.swing.JTable();
        bvalider1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        bexit = new javax.swing.JButton();
        bsupp = new javax.swing.JButton();
        bmodifier = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(208, 227, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pajoutervr.setBackground(new java.awt.Color(247, 242, 235));
        pajoutervr.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pajoutervr.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pajoutervr.add(tnomvar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 240, 30));
        pajoutervr.add(tstyle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 240, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ihm/dress_line.png"))); // NOI18N
        jLabel2.setToolTipText("");
        pajoutervr.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 40, 60));

        jLabel3.setText("Nom :");
        pajoutervr.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jLabel4.setText("Style :");
        pajoutervr.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 78, 172));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ihm/close_fill.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        pajoutervr.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 0, 30, 30));

        bajoute.setBackground(new java.awt.Color(51, 78, 172));
        bajoute.setForeground(new java.awt.Color(255, 255, 255));
        bajoute.setText("Ajouter");
        bajoute.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bajouteMouseClicked(evt);
            }
        });
        bajoute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bajouteActionPerformed(evt);
            }
        });
        pajoutervr.add(bajoute, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 100, -1));

        bmodify.setBackground(new java.awt.Color(51, 78, 172));
        bmodify.setForeground(new java.awt.Color(255, 255, 255));
        bmodify.setText("Modifier");
        bmodify.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bmodifyMouseClicked(evt);
            }
        });
        bmodify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmodifyActionPerformed(evt);
            }
        });
        bmodify.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                bmodifyAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        pajoutervr.add(bmodify, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 100, -1));

        jPanel1.add(pajoutervr, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 580, 270));

        tabVariante.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabVariante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabVarianteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabVariante);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 580, 310));

        bvalider1.setBackground(new java.awt.Color(255, 255, 255));
        bvalider1.setForeground(new java.awt.Color(51, 78, 172));
        bvalider1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ihm/choice_fill.png"))); // NOI18N
        bvalider1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bvalider1MouseClicked(evt);
            }
        });
        jPanel1.add(bvalider1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 60, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setForeground(new java.awt.Color(51, 78, 172));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ihm/add_fill (2).png"))); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 110, -1, -1));

        bexit.setBackground(new java.awt.Color(255, 255, 255));
        bexit.setForeground(new java.awt.Color(51, 78, 172));
        bexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ihm/exit_fill.png"))); // NOI18N
        bexit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bexitMouseClicked(evt);
            }
        });
        bexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bexitActionPerformed(evt);
            }
        });
        jPanel1.add(bexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 160, -1, -1));

        bsupp.setBackground(new java.awt.Color(255, 255, 255));
        bsupp.setForeground(new java.awt.Color(255, 255, 255));
        bsupp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ihm/delete_2_line.png"))); // NOI18N
        bsupp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bsuppMouseClicked(evt);
            }
        });
        bsupp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsuppActionPerformed(evt);
            }
        });
        jPanel1.add(bsupp, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 210, -1, 40));

        bmodifier.setBackground(new java.awt.Color(255, 255, 255));
        bmodifier.setForeground(new java.awt.Color(51, 78, 172));
        bmodifier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ihm/edit_line.png"))); // NOI18N
        bmodifier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bmodifierMouseClicked(evt);
            }
        });
        bmodifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmodifierActionPerformed(evt);
            }
        });
        jPanel1.add(bmodifier, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 260, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("LISTE DES VARIANTES ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bvalider1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bvalider1MouseClicked
        afficher(tabVariante.getSelectedRow());
        Modeles.tidvar.setVisible(true);
        Modeles.tnomvar.setVisible(true);
        Modeles.tstylevar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bvalider1MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        pajoutervr.setVisible(true);
        tabVariante.setVisible(false);
        jScrollPane1.setVisible(false);


    }//GEN-LAST:event_jButton1MouseClicked

    private void bexitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bexitMouseClicked
        this.dispose();
    }//GEN-LAST:event_bexitMouseClicked

    private void bexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bexitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bexitActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        pajoutervr.setVisible(false);
        jScrollPane1.setVisible(true);
        tabVariante.setVisible(true);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void bajouteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bajouteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bajouteActionPerformed

    private void bajouteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bajouteMouseClicked
        boolean vide = false;

        // recuperer les donnees du formulaire
        String nom = tnomvar1.getText();
        String style = tstyle1.getText();

        if (nom.equals("") || style.equals("")) {
            vide = true;
        }

        if (vide == false) {
            Pattern pattern = Pattern.compile("[^a-zA-Z]");
            Matcher matchernom = pattern.matcher(nom);
            Matcher matcherS = pattern.matcher(style);
            if (matchernom.find() || matcherS.find()) {

                JOptionPane.showMessageDialog(null, "la saisie n'est pas valide");
            } else {
                Variante vr = new Variante();
                vr.setNom(nom);
                vr.setStyle(style);

                ConnectVariante cvr = new ConnectVariante();
                boolean varianteExiste = false;
                try {
                    while (cvr.rs.next()) {
                        if (nom.equals(cvr.rs.getString("nom")) && style.equals(cvr.rs.getString("style"))) {
                            varianteExiste = true;
                            break;
                        }
                    }
                    if (!varianteExiste) {
                        stat = co.getCo().createStatement();
                        stat.executeUpdate("INSERT INTO variantes(nom,style) VALUES('"
                                + vr.getNom() + "','" + vr.getStyle() + "')");
                        JOptionPane.showMessageDialog(null, "variante ajouter avec succes");
                       
                        reinitialiser();
                         
                        pajoutervr.setVisible(false);
                        bmodifier.setVisible(false);
                        bsupp.setVisible(false);
                        jScrollPane1.setVisible(true);
                        tabVariante.setVisible(true);
                        actualiser();
                    } else {
                        JOptionPane.showMessageDialog(null, "La variante existe déjà");
                    }

                } catch (SQLException ex) {
                    Logger.getLogger(Employes.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

        } else {
            JOptionPane.showMessageDialog(null, "Vous devez remplir tous les champs");
        }

    }//GEN-LAST:event_bajouteMouseClicked

    private void bsuppMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bsuppMouseClicked
        if (JOptionPane.showConfirmDialog(this, "voulez vous vraiment supprimer ?", "suppression", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            try {
                stat = co.getCo().createStatement();
                stat.executeUpdate("DELETE FROM variantes WHERE id='" + tabVariante.getValueAt(tabVariante.getSelectedRow(), 0) + "'");
                JOptionPane.showMessageDialog(this, "suppression faite avec succes");
                actualiser();

                reinitialiser();
            } catch (SQLException ex) {
                Logger.getLogger(ListeDesVariantes.class.getName()).log(Level.SEVERE, null, ex);
            }
            bmodifier.setVisible(false);
            bsupp.setVisible(false);
        }
    }//GEN-LAST:event_bsuppMouseClicked

    private void bsuppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsuppActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bsuppActionPerformed

    private void bmodifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmodifyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bmodifyActionPerformed

    private void bmodifierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bmodifierMouseClicked
        pajoutervr.setVisible(true);
        jScrollPane1.setVisible(false);
        int nligne = tabVariante.getSelectedRow();
        tnomvar1.setText(tabVariante.getValueAt(nligne, 1).toString());
        tstyle1.setText(tabVariante.getValueAt(nligne, 2).toString());
        bmodify.setVisible(true);
    }//GEN-LAST:event_bmodifierMouseClicked

    private void bmodifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmodifierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bmodifierActionPerformed

    private void bmodifyAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_bmodifyAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_bmodifyAncestorAdded

    private void bmodifyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bmodifyMouseClicked
        if (JOptionPane.showConfirmDialog(this, "voullez vous vraiment modifier ?", "modification",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            String nom = tnomvar1.getText();
            String style = tstyle1.getText();

            boolean vide = false;

            if (nom.equals("") || style.equals("")) {
                vide = true;
            }
            if (vide == false) {
                try {
                    ps = co.getCo().prepareStatement("UPDATE variantes SET nom=?,"
                            + "style=? WHERE id=?");
                    ps.setString(1, nom);
                    ps.setString(2, style);

                    ps.setInt(3, Integer.parseInt(tabVariante.getValueAt(tabVariante.getSelectedRow(), 0) + ""));
                    ps.execute();
                    JOptionPane.showMessageDialog(this, "Modification faite avec succes");
                    actualiser();
                    reinitialiser();
                } catch (SQLException ex) {
                    Logger.getLogger(Employes.class.getName()).log(Level.SEVERE, null, ex);
                }

            } else {
                JOptionPane.showMessageDialog(null, "Vous devez remplir tous les champs");
            }
            pajoutervr.setVisible(false);
            jScrollPane1.setVisible(true);
            bmodifier.setVisible(false);
            bsupp.setVisible(false);
        }
    }//GEN-LAST:event_bmodifyMouseClicked

    private void tabVarianteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabVarianteMouseClicked
        bmodifier.setVisible(true);
        bsupp.setVisible(true);
    }//GEN-LAST:event_tabVarianteMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListeDesVariantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListeDesVariantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListeDesVariantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListeDesVariantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListeDesVariantes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bajoute;
    private javax.swing.JButton bexit;
    private javax.swing.JButton bmodifier;
    public static javax.swing.JButton bmodify;
    private javax.swing.JButton bsupp;
    public static javax.swing.JButton bvalider1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pajoutervr;
    public static javax.swing.JTable tabVariante;
    public static javax.swing.JTextField tnomvar1;
    public static javax.swing.JTextField tstyle1;
    // End of variables declaration//GEN-END:variables
}
