/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vue;

import Model.*;

import java.awt.HeadlessException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;

/**
 *
 * @author toshiba
 */
public class ListeDesClommandess extends javax.swing.JFrame {

    Connexion c = new Connexion();
    Statement stat;
    PreparedStatement prestate;
    ResultSet rs;
    DefaultTableModel dtm = new DefaultTableModel();

    public ListeDesClommandess(JPanel jPanel1, JScrollPane jScrollPane1, JTable jTable1) throws HeadlessException {

        this.jPanel1 = jPanel1;
        this.jScrollPane1 = jScrollPane1;
        this.tablecommande = jTable1;
    }
    ConnectClients cc = new ConnectClients();

    public ListeDesClommandess() {
        initComponents();
        setLocationRelativeTo(this);

        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        actualiser();

    }

    public void actualiser() {
        dtm.setColumnCount(0);
        dtm.setRowCount(0);
        try {
            cc.ps = cc.co.getCo().prepareStatement("SELECT* FROM commandes_pa WHERE etat='Terminée'");
            cc.rs = cc.ps.executeQuery();
        } catch (SQLException ex) {
            Logger.getLogger(ListeDesClommandess.class.getName()).log(Level.SEVERE, null, ex);
        }

        dtm.addColumn("id");
        dtm.addColumn("date");

        dtm.addColumn("id_magasin");
        dtm.addColumn("id_modele");
        dtm.addColumn("quantité");
        dtm.addColumn("etat");

        try {
            while (cc.rs.next()) {
                dtm.addRow(new Object[]{
                    cc.rs.getInt("id"), cc.rs.getDate("date"), cc.rs.getInt("magasin"), cc.rs.getInt("id_modele"), cc.rs.getInt("quentite"), cc.rs.getString("etat")
                });
            }
            tablecommande.setModel(dtm);
        } catch (SQLException ex) {
            Logger.getLogger(ListeDesClommandess.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void affichage(int nligne) {

        Factures.idcommande.setText(tablecommande.getValueAt(nligne, 0).toString());
        int q=Integer.parseInt(tablecommande.getValueAt(nligne, 4).toString());
        Factures.lqte.setText(tablecommande.getValueAt(nligne, 4).toString());

        try {
            stat = c.getCo().createStatement();
            rs = stat.executeQuery("SELECT id,nom,addresse FROM magasin WHERE id=" + Integer.parseInt(tablecommande.getValueAt(nligne, 2).toString()));

            if (rs.next()) {

                // Si le ResultSet contient des lignes, récupérez les données
                Factures.idmagasin1.setText(rs.getString("id"));
                Factures.nommagasin.setText(rs.getString("nom"));
                Factures.addressemagasin.setText(rs.getString("addresse"));
                Factures.addressemagasin.setVisible(true);
                Factures.nommagasin.setVisible(true);
                Factures.lidc.setVisible(true);
                Factures.lq.setVisible(true);
                Factures.lnm.setVisible(true);
                Factures.lidm.setVisible(true);
                Factures.laddm.setVisible(true);
                Factures.lqte.setVisible(true);
                Factures.idcommande.setVisible(true);
                Factures.idmagasin1.setVisible(true);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Mesures.class.getName()).log(Level.SEVERE, null, ex);
        }
         try {
            stat = c.getCo().createStatement();
            rs = stat.executeQuery("SELECT prix FROM modeles WHERE id=" + Integer.parseInt(tablecommande.getValueAt(nligne, 3).toString()));

            if (rs.next()) {
                int p=rs.getInt("prix");
                int t=q*p;
            Factures.ttotale.setText(t+"");
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(Mesures.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bvalider = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablecommande = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(20, 0, 0, 0));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(208, 227, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bvalider.setBackground(new java.awt.Color(255, 255, 255));
        bvalider.setForeground(new java.awt.Color(51, 78, 172));
        bvalider.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ihm/choice_fill.png"))); // NOI18N
        bvalider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bvaliderMouseClicked(evt);
            }
        });
        bvalider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bvaliderActionPerformed(evt);
            }
        });
        jPanel1.add(bvalider, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 50, -1, -1));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setForeground(new java.awt.Color(51, 78, 172));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ihm/exit_fill.png"))); // NOI18N
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 100, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("LISTE DES COMMANDES ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        tablecommande.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablecommande);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 590, 220));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bvaliderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bvaliderMouseClicked

        int selectedRow = tablecommande.getSelectedRow();
        affichage(selectedRow);
        this.setVisible(false);
    }//GEN-LAST:event_bvaliderMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        this.dispose();
    }//GEN-LAST:event_jButton2MouseClicked

    private void bvaliderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bvaliderActionPerformed

    }//GEN-LAST:event_bvaliderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListeDesClommandess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListeDesClommandess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListeDesClommandess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListeDesClommandess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListeDesClommandess().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton bvalider;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tablecommande;
    // End of variables declaration//GEN-END:variables
}
