/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vue;

import Beans.Client;
import Model.*;
import static Vue.Clients.reinitialiser;

import java.awt.HeadlessException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;

/**
 *
 * @author toshiba
 */
public class ListeDesClientss extends javax.swing.JFrame {

    Connexion c = new Connexion();
    Statement stat;
    PreparedStatement prestate;
    ResultSet rs;
    DefaultTableModel dtm = new DefaultTableModel();

    public ListeDesClientss(JPanel jPanel1, JScrollPane jScrollPane1, JTable jTable1) throws HeadlessException {

        this.jPanel1 = jPanel1;
        this.jScrollPane1 = jScrollPane1;
        this.tableclient = jTable1;
    }
    ConnectClients cc = new ConnectClients();

    public ListeDesClientss() {
        initComponents();
        setLocationRelativeTo(this);
        pajoutercl.setVisible(false);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        pajoutercl.setVisible(false);
        actualiser();
        tvage.setVisible(false);

    }

    public void actualiser() {
        dtm.setColumnCount(0);
        dtm.setRowCount(0);
        try {
            cc.ps = cc.co.getCo().prepareStatement("SELECT* FROM clients");
            cc.rs = cc.ps.executeQuery();
        } catch (SQLException ex) {
            Logger.getLogger(ListeDesClientss.class.getName()).log(Level.SEVERE, null, ex);
        }

        dtm.addColumn("id");
        dtm.addColumn("nom");
        dtm.addColumn("prenom");
        dtm.addColumn("age");
        dtm.addColumn("sex");
        dtm.addColumn("adresse");

        try {
            while (cc.rs.next()) {
                dtm.addRow(new Object[]{
                    cc.rs.getInt("id"), cc.rs.getString("nom"), cc.rs.getString("prenom"), cc.rs.getInt("age"), cc.rs.getString("sex"), cc.rs.getString("adresse")
                });
            }
            tableclient.setModel(dtm);
        } catch (SQLException ex) {
            Logger.getLogger(ListeDesClientss.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void affichage(int nligne) {

        if (nligne >= 0 && nligne < tableclient.getRowCount()) {
            Commande.tclientId.setText(tableclient.getValueAt(nligne, 0).toString());
            Commande.tnom.setText(tableclient.getValueAt(nligne, 1).toString());
            Commande.tprenom.setText(tableclient.getValueAt(nligne, 2).toString());
        } 

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bvalider = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        pajoutercl = new javax.swing.JPanel();
        tnom = new javax.swing.JTextField();
        tprenom = new javax.swing.JTextField();
        tage1 = new javax.swing.JTextField();
        tadresse = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cmsex = new javax.swing.JComboBox<>();
        bajouter = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        tvage = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableclient = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(20, 0, 0, 0));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(208, 227, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bvalider.setBackground(new java.awt.Color(255, 255, 255));
        bvalider.setForeground(new java.awt.Color(51, 78, 172));
        bvalider.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ihm/choice_fill.png"))); // NOI18N
        bvalider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bvaliderMouseClicked(evt);
            }
        });
        bvalider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bvaliderActionPerformed(evt);
            }
        });
        jPanel1.add(bvalider, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 40, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setForeground(new java.awt.Color(51, 78, 172));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ihm/user_add_fill.png"))); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 90, -1, -1));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setForeground(new java.awt.Color(51, 78, 172));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ihm/exit_fill.png"))); // NOI18N
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 140, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("LISTE DES CLIENTS ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        pajoutercl.setBackground(new java.awt.Color(247, 242, 235));
        pajoutercl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pajoutercl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pajoutercl.add(tnom, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 180, 30));
        pajoutercl.add(tprenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 180, 30));

        tage1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tage1FocusGained(evt);
            }
        });
        pajoutercl.add(tage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 180, 30));

        tadresse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tadresseActionPerformed(evt);
            }
        });
        pajoutercl.add(tadresse, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, 180, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ihm/user_add_line.png"))); // NOI18N
        pajoutercl.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 40, 60));

        jLabel3.setText("Nom");
        pajoutercl.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jLabel4.setText("Prenom");
        pajoutercl.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jLabel5.setText("age");
        pajoutercl.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        jLabel6.setText("sex");
        pajoutercl.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, -1, -1));

        jLabel7.setText("Adresse");
        pajoutercl.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, -1, -1));

        cmsex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "homme", "femme" }));
        pajoutercl.add(cmsex, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, 180, 30));

        bajouter.setBackground(new java.awt.Color(51, 78, 172));
        bajouter.setForeground(new java.awt.Color(255, 255, 255));
        bajouter.setText("ajouter");
        bajouter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bajouterMouseClicked(evt);
            }
        });
        pajoutercl.add(bajouter, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 240, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 78, 172));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ihm/close_fill.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        pajoutercl.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, 30, 30));

        tvage.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        tvage.setForeground(new java.awt.Color(255, 0, 0));
        tvage.setText("la valeur de l'age est incorrect");
        pajoutercl.add(tvage, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, -1, 20));

        jPanel1.add(pajoutercl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 600, 260));

        tableclient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableclient);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 590, 220));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bvaliderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bvaliderMouseClicked

        int selectedRow = tableclient.getSelectedRow();
        if (selectedRow != -1) {
            affichage(selectedRow);
            Commande.lcid.setVisible(true);
            Commande.lcnom.setVisible(true);
            Commande.lcprenom.setVisible(true);
            Commande.tclientId.setVisible(true);
            Commande.tnom.setVisible(true);
            Commande.tprenom.setVisible(true);
        } else {
            System.out.println(selectedRow);
        }

        this.setVisible(false);
    }//GEN-LAST:event_bvaliderMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        this.dispose();
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        pajoutercl.setVisible(true);
        jScrollPane1.setVisible(false);


    }//GEN-LAST:event_jButton1MouseClicked

    private void tadresseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tadresseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tadresseActionPerformed

    private void bajouterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bajouterMouseClicked
       String nom = tnom.getText();
        String prenom = tprenom.getText();
        int age;
        String sex = cmsex.getSelectedItem().toString();
        String adresse = tadresse.getText();

        boolean vide = false;
        boolean vage = true;
        // recuperer les donnees du formulaire

        if (nom.equals("") || prenom.equals("") || tage1.getText().equals("") || adresse.equals("")) {
            vide = true;
        }

        if (vide == false) {
            
            Pattern pattern = Pattern.compile("[^a-zA-Z]");
            Matcher matchernom = pattern.matcher(nom);
            Matcher matcherprenom = pattern.matcher(prenom);
            Pattern pattern2 = Pattern.compile("[^0-9]");
            Matcher matcherage = pattern2.matcher(tage1.getText());

            if (matchernom.find() || matcherprenom.find() || matcherage.find()) {

                JOptionPane.showMessageDialog(null, "la saisie n'est pas valide");
            } else {

                age = Integer.parseInt(tage1.getText());
                if (age > 100 || age <= 0) {
                    vage = false;
                }
                if (vage) {
                    Client cl = new Client();
                    cl.setNom(nom);
                    cl.setPrenom(prenom);
                    cl.setAge(age);
                    cl.setsex(sex);
                    cl.setAdresse(adresse);
                    try {
                        stat = c.getCo().createStatement();
                        stat.executeUpdate("INSERT INTO clients(nom,prenom,age,sex,adresse) VALUES('"
                                + cl.getNom() + "','" + cl.getPrenom() + "','" + cl.getAge() + "','" + cl.getsex() + "','" + cl.getAdresse() + "')");
                        JOptionPane.showMessageDialog(null, "Clients ajouter avec succes");
                        actualiser();
                        reinitialiser();

                    } catch (SQLException ex) {
                        Logger.getLogger(ListeDesClientss.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    pajoutercl.setVisible(false);
                    jScrollPane1.setVisible(true);
                } else {
                    tvage.setVisible(true);
                }

            }

        } else {
            JOptionPane.showMessageDialog(null, "Vous devez remplir tous les champs");
        }

    }//GEN-LAST:event_bajouterMouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        pajoutercl.setVisible(false);
        jScrollPane1.setVisible(true);

    }//GEN-LAST:event_jLabel8MouseClicked

    private void bvaliderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bvaliderActionPerformed

    }//GEN-LAST:event_bvaliderActionPerformed

    private void tage1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tage1FocusGained
        tvage.setVisible(false);
    }//GEN-LAST:event_tage1FocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListeDesClientss.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListeDesClientss.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListeDesClientss.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListeDesClientss.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListeDesClientss().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bajouter;
    public static javax.swing.JButton bvalider;
    private javax.swing.JComboBox<String> cmsex;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pajoutercl;
    public static javax.swing.JTable tableclient;
    private javax.swing.JTextField tadresse;
    private javax.swing.JTextField tage1;
    private javax.swing.JTextField tnom;
    private javax.swing.JTextField tprenom;
    public static javax.swing.JLabel tvage;
    // End of variables declaration//GEN-END:variables
}
