/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vue;

import Model.*;
import java.awt.HeadlessException;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;

/**
 *
 * @author toshiba
 */
public class ListeDesModeles extends javax.swing.JFrame {
 
    /**
     * Creates new form ListeDesStagiaires
     */
   ConnetModeles cm = new ConnetModeles();
    Statement stat;
    Connexion co = new Connexion();
    PreparedStatement ps;
  

    public ListeDesModeles(JPanel jPanel1, JScrollPane jScrollPane1, JTable jTable1) throws HeadlessException {
        
        this.jPanel1 = jPanel1;
        this.jScrollPane1 = jScrollPane1;
        this.tabModele = jTable1;
    }
  ConnectClients cc=new ConnectClients();
     DefaultTableModel dtm= new DefaultTableModel();
    public ListeDesModeles() {
        initComponents();
        setLocationRelativeTo(this);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        actualiser();
       
    }
    public void afficher(int nligne) {
        Commande.jmi.setText(tabModele.getValueAt(nligne, 0).toString());
        Commande.jmn.setText(tabModele.getValueAt(nligne, 1).toString());
        
    
    }
   
    public void actualiser() {
        //vider la table
        dtm.setColumnCount(0);
        dtm.setRowCount(0);
        try {
            cm.ps = cm.co.getCo().prepareStatement("SELECT* FROM modeles");
            cm.rs = cm.ps.executeQuery();
        } catch (SQLException ex) {
            Logger.getLogger(Modeles.class.getName()).log(Level.SEVERE, null, ex);
        }

        dtm.addColumn("id");
        dtm.addColumn("nom");
        dtm.addColumn("prix");
        dtm.addColumn("image");
        dtm.addColumn("id_variante");

        try {
            while (cm.rs.next()) {
                dtm.addRow(new Object[]{
                    cm.rs.getString("id"), cm.rs.getString("nom"), cm.rs.getInt("prix"),
                    cm.rs.getBlob("image"), cm.rs.getInt("id_variant")

                });
            }
            tabModele.setModel(dtm);
        } catch (SQLException ex) {
            Logger.getLogger(Modeles.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabModele = new javax.swing.JTable();
        bvalider1 = new javax.swing.JButton();
        bexit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(208, 227, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabModele.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabModele);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 580, 310));

        bvalider1.setBackground(new java.awt.Color(255, 255, 255));
        bvalider1.setForeground(new java.awt.Color(51, 78, 172));
        bvalider1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ihm/choice_fill.png"))); // NOI18N
        bvalider1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bvalider1MouseClicked(evt);
            }
        });
        jPanel1.add(bvalider1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 60, -1, -1));

        bexit.setBackground(new java.awt.Color(255, 255, 255));
        bexit.setForeground(new java.awt.Color(51, 78, 172));
        bexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ihm/exit_fill.png"))); // NOI18N
        bexit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bexitMouseClicked(evt);
            }
        });
        bexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bexitActionPerformed(evt);
            }
        });
        jPanel1.add(bexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 110, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("LISTE DES MODELES ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bvalider1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bvalider1MouseClicked
      afficher(tabModele.getSelectedRow());
      Commande.jLmi.setVisible(true);
       Commande.jlmn.setVisible(true);
       
         Commande.jmi.setVisible(true);
          Commande.jmn.setVisible(true);
           
      this.setVisible(false);
    }//GEN-LAST:event_bvalider1MouseClicked

    private void bexitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bexitMouseClicked
        this.dispose();
    }//GEN-LAST:event_bexitMouseClicked

    private void bexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bexitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bexitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListeDesModeles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListeDesModeles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListeDesModeles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListeDesModeles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListeDesModeles().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bexit;
    public static javax.swing.JButton bvalider1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tabModele;
    // End of variables declaration//GEN-END:variables
}
