/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vue;

import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import Model.*;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author toshiba
 */
public class Modeles extends javax.swing.JPanel {

    ConnetModeles cm = new ConnetModeles();
    Statement stat;
    Statement stat1;
    Statement stat2;
    Connexion co = new Connexion();
    PreparedStatement ps;
    ListeDesVariantes lv = new ListeDesVariantes();
    ResultSet rs;

    DefaultTableModel dtm = new DefaultTableModel();

    public Modeles() {
        initComponents();
        actualiser();
        reinisialisation();

    }

    public void reinisialisation() {

        tnom.setText("");
        tprix.setText("");
        tpath.setText("");

        tidvar.setText("");
        tnomvar.setVisible(false);
        tstylevar.setVisible(false);
        lphoto.setIcon(null);
        bmodifier.setVisible(false);
        bsupp.setVisible(false);

    }

    public void afficher(int nligne) {
        tnom.setText(tabmodele.getValueAt(nligne, 1).toString());
        tprix.setText(tabmodele.getValueAt(nligne, 2).toString());
        tidvar.setText(tabmodele.getValueAt(nligne, 4).toString());
        tidvar.setVisible(true);
        try {
            cm.ps = cm.co.getCo().prepareStatement("SELECT path FROM modeles where id=" + tabmodele.getValueAt(nligne, 0));
            cm.rs = cm.ps.executeQuery();
            if (cm.rs.next()) {
                String valeur = cm.rs.getString("path");
                tpath.setText(valeur);
                ImageIcon img = new ImageIcon(valeur);
                Image imgrec = img.getImage();

                Image nimage = imgrec.getScaledInstance(lphoto.getWidth(),
                        lphoto.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon imgfinal = new ImageIcon(nimage);

                lphoto.setIcon(imgfinal);

            }

        } catch (SQLException ex) {
            Logger.getLogger(Modeles.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            stat = co.getCo().createStatement();
            rs = stat.executeQuery("SELECT nom,style FROM variantes WHERE id=" + Integer.parseInt(tabmodele.getValueAt(nligne, 4).toString()));

            if (rs.next()) {

                // Si le ResultSet contient des lignes, récupérez les données
                tnomvar.setText(rs.getString("nom"));
                tstylevar.setText(rs.getString("style"));
                tnomvar.setVisible(true);
                tstylevar.setVisible(true);

            }
        } catch (SQLException ex) {
            Logger.getLogger(Modeles.class.getName()).log(Level.SEVERE, null, ex);
        }
        bmodifier.setVisible(false);
        bsupp.setVisible(false);

    }

    public void actualiser() {
        //vider la table
        dtm.setColumnCount(0);
        dtm.setRowCount(0);
        try {
            cm.ps = cm.co.getCo().prepareStatement("SELECT* FROM modeles");
            cm.rs = cm.ps.executeQuery();
        } catch (SQLException ex) {
            Logger.getLogger(Modeles.class.getName()).log(Level.SEVERE, null, ex);
        }

        dtm.addColumn("id");
        dtm.addColumn("nom");
        dtm.addColumn("prix");
        dtm.addColumn("image");
        dtm.addColumn("id_variante");

        try {
            while (cm.rs.next()) {
                dtm.addRow(new Object[]{
                    cm.rs.getString("id"), cm.rs.getString("nom"), cm.rs.getInt("prix"),
                    cm.rs.getBlob("image"), cm.rs.getInt("id_variant")

                });
            }
            tabmodele.setModel(dtm);
        } catch (SQLException ex) {
            Logger.getLogger(Modeles.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tnom = new javax.swing.JTextField();
        tprix = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        lphoto = new javax.swing.JLabel();
        bcharger = new javax.swing.JButton();
        tpath = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        bsupp = new javax.swing.JButton();
        bmodifier = new javax.swing.JButton();
        bAjoute = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        tidvar = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        tstylevar = new javax.swing.JLabel();
        selecVariante = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        tnomvar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabmodele = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        brecherch = new javax.swing.JButton();
        trecherche = new javax.swing.JTextField();
        cmchoix = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(770, 550));
        setPreferredSize(new java.awt.Dimension(770, 550));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setToolTipText("");
        jPanel1.setMinimumSize(new java.awt.Dimension(770, 550));
        jPanel1.setPreferredSize(new java.awt.Dimension(770, 550));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(247, 242, 235));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Variante :");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, -1, -1));

        jLabel3.setText("Nom :");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel5.setText("Prix :");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));
        jPanel2.add(tnom, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 200, 30));
        jPanel2.add(tprix, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 200, 30));

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lphoto, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lphoto, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, 210, 160));

        bcharger.setBackground(new java.awt.Color(51, 78, 172));
        bcharger.setForeground(new java.awt.Color(255, 255, 255));
        bcharger.setText("Charger");
        bcharger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bchargerActionPerformed(evt);
            }
        });
        jPanel2.add(bcharger, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 210, 210, -1));

        tpath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tpathActionPerformed(evt);
            }
        });
        jPanel2.add(tpath, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, 210, -1));

        jButton6.setBackground(new java.awt.Color(51, 78, 172));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ihm/refresh_3_fill.png"))); // NOI18N
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, 50, 30));

        bsupp.setBackground(new java.awt.Color(51, 78, 172));
        bsupp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ihm/delete_2_fill.png"))); // NOI18N
        bsupp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bsuppMouseClicked(evt);
            }
        });
        jPanel2.add(bsupp, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 90, 40));

        bmodifier.setBackground(new java.awt.Color(51, 78, 172));
        bmodifier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ihm/pencil_2_fill.png"))); // NOI18N
        bmodifier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bmodifierMouseClicked(evt);
            }
        });
        jPanel2.add(bmodifier, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 90, 40));

        bAjoute.setBackground(new java.awt.Color(51, 78, 172));
        bAjoute.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ihm/add_fill.png"))); // NOI18N
        bAjoute.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bAjouteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bAjouteMouseEntered(evt);
            }
        });
        bAjoute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAjouteActionPerformed(evt);
            }
        });
        jPanel2.add(bAjoute, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 90, 40));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tidvar.setText(".........");
        jPanel5.add(tidvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, -1, 20));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 140, 30));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tstylevar.setText(".........");
        jPanel6.add(tstylevar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, -1, 20));

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 140, 30));

        selecVariante.setBackground(new java.awt.Color(204, 204, 255));
        selecVariante.setForeground(new java.awt.Color(51, 78, 172));
        selecVariante.setText("+ selectionner");
        selecVariante.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        selecVariante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selecVarianteMouseClicked(evt);
            }
        });
        jPanel2.add(selecVariante, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, -1, -1));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tnomvar.setText(".........");
        jPanel7.add(tnomvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, -1, 20));

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 140, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 740, 260));

        tabmodele.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabmodele.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabmodeleMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabmodele);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 740, 230));

        jPanel4.setBackground(new java.awt.Color(254, 237, 245));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        brecherch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ihm/search_2_fill (1).png"))); // NOI18N
        brecherch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                brecherchMouseClicked(evt);
            }
        });
        brecherch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brecherchActionPerformed(evt);
            }
        });
        jPanel4.add(brecherch, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, 50, 30));

        trecherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trechercheActionPerformed(evt);
            }
        });
        trecherche.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                trechercheFocusGained(evt);
            }
        });
        jPanel4.add(trecherche, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 20, 130, 30));

        cmchoix.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Id", "Nom" }));
        cmchoix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmchoixActionPerformed(evt);
            }
        });
        jPanel4.add(cmchoix, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, 80, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ihm/modele2.jpg"))); // NOI18N
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 70));

        jLabel8.setText("Rechercher par :");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("MODELES");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 130, 20));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 70));

        jButton2.setBackground(new java.awt.Color(51, 78, 172));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ihm/refresh_3_fill.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 20, 50, 30));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 600));
    }// </editor-fold>//GEN-END:initComponents

    private void bchargerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bchargerActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        //préciser le dossier ou se trouvent les images
        fileChooser.setCurrentDirectory(new File("C:\\Users\\toshiba\\Desktop\\modeles"));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Image", "jpg", "png", "gif");
        fileChooser.addChoosableFileFilter(filter);
        int result = fileChooser.showOpenDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            File fichierselectionne = fileChooser.getSelectedFile();
            String path = fichierselectionne.getAbsolutePath();
            ImageIcon img = new ImageIcon(path);
            Image imgrec = img.getImage();

            Image nimage = imgrec.getScaledInstance(lphoto.getWidth(),
                    lphoto.getHeight(), Image.SCALE_SMOOTH);

            ImageIcon imgfinal = new ImageIcon(nimage);

            lphoto.setIcon(imgfinal);

            tpath.setText(path);
        } else if (result == JFileChooser.CANCEL_OPTION) {
            JOptionPane.showMessageDialog(null, "Aucun choix effectué");
        }

    }//GEN-LAST:event_bchargerActionPerformed

    private void trechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trechercheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_trechercheActionPerformed

    private void brecherchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brecherchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_brecherchActionPerformed

    private void bAjouteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAjouteActionPerformed

    }//GEN-LAST:event_bAjouteActionPerformed

    private void cmchoixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmchoixActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmchoixActionPerformed

    private void tabmodeleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabmodeleMouseClicked
        afficher(tabmodele.getSelectedRow());
        bmodifier.setVisible(true);
        bsupp.setVisible(true);
    }//GEN-LAST:event_tabmodeleMouseClicked

    private void bmodifierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bmodifierMouseClicked

        if (JOptionPane.showConfirmDialog(this, "voullez vous vraiment modifier ?", "modification",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            boolean vide = false;
            // recuperer les donnees du formulaire
            String nom = tnom.getText();
            String prix = tprix.getText();
            Pattern pattern = Pattern.compile("[^a-zA-Z]");
            Matcher matchernom = pattern.matcher(nom);
            Pattern pattern2 = Pattern.compile("[^0-9]");
            Matcher matcherP = pattern2.matcher(tprix.getText());
            if (nom.equals("") || prix.equals("") || tidvar.getText().equals("") || tpath.getText().equals("")) {
                vide = true;
            }
            if (vide == false) {
                if (matchernom.find() || matcherP.find()) {
                    JOptionPane.showMessageDialog(null, "la saisie n'est pas valide");
                } else {

                    try {
                        ps = co.getCo().prepareStatement("UPDATE modeles SET nom=?,"
                                + "prix=?,image=?,path=?,id_variant=? WHERE id=?");
                        ps.setString(1, tnom.getText());
                        ps.setString(2, tprix.getText());
                        // ps.setString(3, tcouleur.getText());
                        InputStream ins = new FileInputStream(tpath.getText());
                        ps.setBlob(3, ins);
                        ps.setString(4, tpath.getText());
                        ps.setInt(5, Integer.parseInt(tidvar.getText()));
                        ps.setInt(6, Integer.parseInt(tabmodele.getValueAt(tabmodele.getSelectedRow(), 0) + ""));
                        ps.execute();
                        JOptionPane.showMessageDialog(this, "Modification faite avec succes");
                        actualiser();
                        reinisialisation();
                    } catch (SQLException ex) {
                        Logger.getLogger(Modeles.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (FileNotFoundException ex) {
                        Logger.getLogger(Modeles.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            } else {
                JOptionPane.showMessageDialog(null, "Vous devez remplir tous les champs");
            }
        }
    }//GEN-LAST:event_bmodifierMouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        actualiser();
        reinisialisation();
    }//GEN-LAST:event_jButton6MouseClicked

    private void bsuppMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bsuppMouseClicked
        if (JOptionPane.showConfirmDialog(this, "voulez vous vraiment supprimer ?", "suppression", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            try {
                stat2 = co.getCo().createStatement();
                stat2.executeUpdate("DELETE FROM commandes_sm WHERE id_modele='" + tabmodele.getValueAt(tabmodele.getSelectedRow(), 0) + "'");
                stat1 = co.getCo().createStatement();
                stat1.executeUpdate("DELETE FROM commandes_pa WHERE id_modele='" + tabmodele.getValueAt(tabmodele.getSelectedRow(), 0) + "'");
                stat = co.getCo().createStatement();
                stat.executeUpdate("DELETE FROM modeles WHERE id='" + tabmodele.getValueAt(tabmodele.getSelectedRow(), 0) + "'");
                JOptionPane.showMessageDialog(this, "suppression faite avec succes");
                actualiser();
                reinisialisation();

            } catch (SQLException ex) {
                Logger.getLogger(Modeles.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_bsuppMouseClicked

    private void brecherchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brecherchMouseClicked
        String s;
        s = cmchoix.getSelectedItem().toString();
        try {

            ps = co.getCo().prepareStatement("SELECT * FROM modeles WHERE " + s + "=?");
            if (s.equals("id")) {
                ps.setInt(1, Integer.parseInt(trecherche.getText()));
            } else {
                ps.setString(1, trecherche.getText());
            }

            cm.rs = ps.executeQuery();
            dtm.setRowCount(0);
            while (cm.rs.next()) {
                dtm.addRow(new Object[]{cm.rs.getInt("id"), cm.rs.getString("nom"), cm.rs.getInt("prix"),
                    cm.rs.getBlob("image"), cm.rs.getInt("id_variant")});
            }
            tabmodele.setModel(dtm);
            if (dtm.getRowCount() != 0) {
                afficher(0);
            } else {
                actualiser();
                JOptionPane.showMessageDialog(this, "le modele n'existe pas");
            }

        } catch (SQLException ex) {
            Logger.getLogger(Modeles.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_brecherchMouseClicked

    private void bAjouteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bAjouteMouseClicked

        boolean vide = false;

        // recuperer les donnees du formulaire
        String nom = tnom.getText();
        String prix = tprix.getText();

        Pattern pattern = Pattern.compile("[^a-zA-Z]");
        Matcher matchernom = pattern.matcher(nom);
        Pattern pattern2 = Pattern.compile("[^0-9]");
        Matcher matcherP = pattern2.matcher(tprix.getText());

        if (nom.equals("") || prix.equals("") || tidvar.getText().equals("") || tpath.getText().equals("")) {
            vide = true;
        }

        if (vide == false) {
            if (matchernom.find() || matcherP.find()) {

                JOptionPane.showMessageDialog(null, "la saisie n'est pas valide");
            } else {

                try {
                    ps = co.getCo().prepareStatement("INSERT INTO modeles (nom,prix,"
                            + "image,path,id_variant) VALUES(?,?,?,?,?)");

                    ps.setString(1, tnom.getText());
                    ps.setString(2, tprix.getText());
                    //ps.setString(3, tcouleur.getText());

                    try {
                        InputStream ins = new FileInputStream(tpath.getText());
                        ps.setBlob(3, ins);
                    } catch (FileNotFoundException ex) {
                        Logger.getLogger(Modeles.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    ps.setString(4, tpath.getText());
                    ps.setString(5, tidvar.getText());
                    ps.execute();
                    JOptionPane.showMessageDialog(null, "modele ajouter avec succes");
                    actualiser();
                    reinisialisation();
                } catch (SQLException ex) {
                    Logger.getLogger(Modeles.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Vous devez remplir tous les champs");
        }


    }//GEN-LAST:event_bAjouteMouseClicked

    private void tpathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tpathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tpathActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        actualiser();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void bAjouteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bAjouteMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_bAjouteMouseEntered

    private void selecVarianteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selecVarianteMouseClicked
        lv.setVisible(true);
        lv.actualiser();
    }//GEN-LAST:event_selecVarianteMouseClicked

    private void trechercheFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_trechercheFocusGained
        reinisialisation();
    }//GEN-LAST:event_trechercheFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAjoute;
    private javax.swing.JButton bcharger;
    private javax.swing.JButton bmodifier;
    private javax.swing.JButton brecherch;
    private javax.swing.JButton bsupp;
    private javax.swing.JComboBox<String> cmchoix;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lphoto;
    private javax.swing.JLabel selecVariante;
    private javax.swing.JTable tabmodele;
    public static javax.swing.JLabel tidvar;
    public static javax.swing.JTextField tnom;
    public static javax.swing.JLabel tnomvar;
    private javax.swing.JTextField tpath;
    public static javax.swing.JTextField tprix;
    private javax.swing.JTextField trecherche;
    public static javax.swing.JLabel tstylevar;
    // End of variables declaration//GEN-END:variables
}
