package Vue;

import Beans.*;
import Model.*;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author toshiba
 */
public class Profile extends javax.swing.JPanel {

    /**
     * Creates new form Enseignant
     */
    Connexion c = new Connexion();
    Statement stat;
    PreparedStatement prestate;
    ResultSet rs;
    DefaultTableModel dtm = new DefaultTableModel();

    public Profile() {
        initComponents();
        actualiser();
        reinitialiser();

    }

    public void reinitialiser() {
        pmodifier.setVisible(false);
        bsuuprimer.setVisible(false);
        tusername.setText(null);
        tpassword.setText(null);
        lerr.setVisible(false);
        try {
    stat = c.getCo().createStatement();
    rs = stat.executeQuery("SELECT nom,addresse FROM aatelier where id=1");
    // Vérifier s'il y a des résultats
    if (rs.next()) {
        tnom1.setText(rs.getString("nom"));
        taddresse.setText(rs.getString("addresse"));
    }
    else{
        tnom1.setText(null);
        taddresse.setText(null);
    }
} catch (SQLException ex) {
    Logger.getLogger(Profile.class.getName()).log(Level.SEVERE, null, ex);
}
    }

    public void actualiser() {
        //vider la table
        dtm.setColumnCount(0);
        dtm.setRowCount(0);
        try {
            stat = c.getCo().createStatement();
            rs = stat.executeQuery("select * from admin");
            dtm.addColumn("identifiant");
            dtm.addColumn("username");
            dtm.addColumn("password");

            while (rs.next()) {
                dtm.addRow(new Object[]{
                    rs.getInt("id"), rs.getString("username"), rs.getString("password")
                });
            }
            tabAdmin.setModel(dtm);
            reinitialiser();

        } catch (SQLException ex) {
            Logger.getLogger(Profile.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void afficher(int nligne) {
        tusername.setText(tabAdmin.getValueAt(nligne, 1).toString());
        tpassword.setText(tabAdmin.getValueAt(nligne, 2).toString());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        penseignanat = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tusername = new javax.swing.JTextField();
        tpassword = new javax.swing.JTextField();
        bsuuprimer = new javax.swing.JButton();
        pmodifier = new javax.swing.JButton();
        bactu = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tnom1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        taddresse = new javax.swing.JTextField();
        pmodifieratt = new javax.swing.JButton();
        lerr = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabAdmin = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        tusernamead = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(770, 550));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(770, 530));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        penseignanat.setBackground(new java.awt.Color(255, 255, 255));
        penseignanat.setPreferredSize(new java.awt.Dimension(770, 530));
        penseignanat.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(247, 242, 235));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Username:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel3.setText("Password:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, -1, -1));

        tusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tusernameActionPerformed(evt);
            }
        });
        tusername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tusernameFocusLost(evt);
            }
        });
        jPanel1.add(tusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 200, 30));

        tpassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tpasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tpasswordFocusLost(evt);
            }
        });
        jPanel1.add(tpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, 200, 30));

        bsuuprimer.setBackground(new java.awt.Color(51, 78, 172));
        bsuuprimer.setForeground(new java.awt.Color(255, 255, 255));
        bsuuprimer.setText("Supprimer");
        bsuuprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsuuprimerActionPerformed(evt);
            }
        });
        jPanel1.add(bsuuprimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 90, 30));

        pmodifier.setBackground(new java.awt.Color(51, 78, 172));
        pmodifier.setForeground(new java.awt.Color(255, 255, 255));
        pmodifier.setText("Modifier");
        pmodifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pmodifierActionPerformed(evt);
            }
        });
        jPanel1.add(pmodifier, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 90, 30));

        bactu.setBackground(new java.awt.Color(51, 78, 172));
        bactu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ihm/refresh_3_fill.png"))); // NOI18N
        bactu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bactuActionPerformed(evt);
            }
        });
        jPanel1.add(bactu, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, 50, 30));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 730, 10));

        jLabel4.setText("INFORMATIONS SUR L'ATELIER");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabel5.setText("INFORMATIONS PERSONNELLES");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        tnom1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tnom1ActionPerformed(evt);
            }
        });
        tnom1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tnom1FocusLost(evt);
            }
        });
        jPanel1.add(tnom1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 200, 30));

        jLabel7.setText("Nom :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jLabel8.setText("Adresse:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, -1, -1));

        taddresse.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                taddresseFocusLost(evt);
            }
        });
        jPanel1.add(taddresse, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, 200, 30));

        pmodifieratt.setBackground(new java.awt.Color(51, 78, 172));
        pmodifieratt.setForeground(new java.awt.Color(255, 255, 255));
        pmodifieratt.setText("Modifier");
        pmodifieratt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pmodifierattMouseClicked(evt);
            }
        });
        pmodifieratt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pmodifierattActionPerformed(evt);
            }
        });
        jPanel1.add(pmodifieratt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 90, 30));

        lerr.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lerr.setForeground(new java.awt.Color(255, 0, 0));
        lerr.setText("le mot de passe doit contenir au moins 8 caracteres");
        jPanel1.add(lerr, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, -1, -1));

        penseignanat.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 730, 280));

        tabAdmin.setGridColor(new java.awt.Color(0, 102, 255));
        tabAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabAdminMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabAdmin);

        penseignanat.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 730, 130));

        jPanel2.setBackground(new java.awt.Color(196, 227, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tusernamead.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tusernamead.setForeground(new java.awt.Color(8, 31, 92));
        tusernamead.setText("...................................... ");
        jPanel2.add(tusernamead, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 30));

        penseignanat.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 50));

        add(penseignanat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1, 770, 550));
    }// </editor-fold>//GEN-END:initComponents

    private void tusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tusernameActionPerformed

    private void tusernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tusernameFocusLost
        if (tusername.getText() != "") {
            tusername.setText(tusername.getText().toUpperCase());
        }

    }//GEN-LAST:event_tusernameFocusLost

    private void tpasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tpasswordFocusLost

    }//GEN-LAST:event_tpasswordFocusLost

    private void tabAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabAdminMouseClicked
        afficher(tabAdmin.getSelectedRow());
        pmodifier.setVisible(true);
        bsuuprimer.setVisible(true);
    }//GEN-LAST:event_tabAdminMouseClicked

    private void bsuuprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsuuprimerActionPerformed
        if (JOptionPane.showConfirmDialog(this, "voulez vous vraiment supprimer ?", "suppression", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            try {
                stat = c.getCo().createStatement();
                stat.executeUpdate("DELETE FROM admin WHERE id='" + tabAdmin.getValueAt(tabAdmin.getSelectedRow(), 0) + "'");
                JOptionPane.showMessageDialog(this, "suppression faite avec succes");
                actualiser();

                reinitialiser();
            } catch (SQLException ex) {
                Logger.getLogger(Profile.class.getName()).log(Level.SEVERE, null, ex);
            }
            reinitialiser();
        }
    }//GEN-LAST:event_bsuuprimerActionPerformed

    private void pmodifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pmodifierActionPerformed
        if (JOptionPane.showConfirmDialog(this, "voullez vous vraiment modifier ?", "modification",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            String username = tusername.getText();
            String passw = tpassword.getText();

            boolean vide = false;
            Pattern pattern = Pattern.compile("[^a-zA-Z]");

            if (username.equals("") || passw.equals("")) {
                vide = true;
            }
            if (vide == false) {
                if (passw.length() < 8) {
                    lerr.setVisible(true);
                } else {
                    try {
                        prestate = c.getCo().prepareStatement("UPDATE admin SET username=?,"
                                + "password=? WHERE id=?");
                        prestate.setString(1, username);
                        prestate.setString(2, passw);

                        prestate.setInt(3, Integer.parseInt(tabAdmin.getValueAt(tabAdmin.getSelectedRow(), 0) + ""));
                        prestate.execute();
                        JOptionPane.showMessageDialog(this, "Modification faite avec succes");
                        actualiser();
                        reinitialiser();
                    } catch (SQLException ex) {
                        Logger.getLogger(Profile.class.getName()).log(Level.SEVERE, null, ex);
                    }

                }

            } else {
                JOptionPane.showMessageDialog(null, "Vous devez remplir tous les champs");
            }

        }
    }//GEN-LAST:event_pmodifierActionPerformed

    private void bactuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bactuActionPerformed
        actualiser();
        reinitialiser();
    }//GEN-LAST:event_bactuActionPerformed

    private void tnom1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnom1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tnom1ActionPerformed

    private void tnom1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tnom1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_tnom1FocusLost

    private void taddresseFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_taddresseFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_taddresseFocusLost

    private void pmodifierattActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pmodifierattActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pmodifierattActionPerformed

    private void tpasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tpasswordFocusGained
        lerr.setVisible(false);
    }//GEN-LAST:event_tpasswordFocusGained

    private void pmodifierattMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pmodifierattMouseClicked
     int nba = 0;
try {
    stat = c.getCo().createStatement();
    rs = stat.executeQuery("SELECT COUNT(*) AS nbe FROM aatelier");
    // Vérifier s'il y a des résultats
    if (rs.next()) {
        nba = rs.getInt("nbe");
    }
} catch (SQLException ex) {
    Logger.getLogger(Profile.class.getName()).log(Level.SEVERE, null, ex);
}

String nom = tnom1.getText();
String adresse = taddresse.getText();
boolean vide = nom.isEmpty() || adresse.isEmpty();

if (!vide) {
    try {
        if (nba == 0) {
            // Aucun atelier existant, ajouter un nouvel atelier
            prestate = c.getCo().prepareStatement("INSERT INTO aatelier(nom, addresse) VALUES (?, ?)");
            prestate.setString(1, nom);
            prestate.setString(2, adresse);
            prestate.executeUpdate();
        } else {
            // Au moins un atelier existant, mise à jour ou insertion en fonction de la présence de l'atelier
            prestate = c.getCo().prepareStatement("UPDATE aatelier SET nom=?,"
                                + "addresse=? WHERE id=?");
            prestate.setString(1, nom);
            prestate.setString(2, adresse);
            prestate.setInt(3, 1);
            prestate.executeUpdate();
        }
        JOptionPane.showMessageDialog(this, "Opération réussie !");
        actualiser();
        reinitialiser();
    } catch (SQLException ex) {
        Logger.getLogger(Profile.class.getName()).log(Level.SEVERE, null, ex);
    }
} else {
    JOptionPane.showMessageDialog(null, "Vous devez remplir tous les champs !");
}


    }//GEN-LAST:event_pmodifierattMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bactu;
    private javax.swing.JButton bsuuprimer;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lerr;
    private javax.swing.JPanel penseignanat;
    private javax.swing.JButton pmodifier;
    private javax.swing.JButton pmodifieratt;
    public static javax.swing.JTable tabAdmin;
    public static javax.swing.JTextField taddresse;
    public static javax.swing.JTextField tnom1;
    public static javax.swing.JTextField tpassword;
    public static javax.swing.JTextField tusername;
    public static javax.swing.JLabel tusernamead;
    // End of variables declaration//GEN-END:variables
}
