package Vue;

import Model.Connexion;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author toshiba
 */
public class SeancesE extends javax.swing.JPanel {

    PreparedStatement ps;
    Connexion co = new Connexion();
    DefaultTableModel dtm = new DefaultTableModel();
    Statement stat;
    ResultSet rs;
    ListeDesClommandeSm lcm = new ListeDesClommandeSm();

    public SeancesE() {
        initComponents();
        actualiser();
        reinitialiser();
    }

    public void reinitialiser() {
        tdate1.setDate(null);
        idcommande.setText("");
        idclient.setVisible(false);
        nomclient.setVisible(false);
        prenomclient.setVisible(false);
        lidc.setVisible(false);
        lidm.setVisible(false);
        lnm.setVisible(false);
        laddm.setVisible(false);
        bsuuprimer.setVisible(false);
        pmodifier.setVisible(false);

    }

    public void actualiser() {
        //vider la table
        dtm.setColumnCount(0);
        dtm.setRowCount(0);
        try {
            stat = co.getCo().createStatement();
            rs = stat.executeQuery("select * from seances_dessayage");
            dtm.addColumn("numero");
            dtm.addColumn("date");
            dtm.addColumn("heure");
            dtm.addColumn("id_commande");

            while (rs.next()) {
                dtm.addRow(new Object[]{
                    rs.getInt("id"), rs.getDate("date"), rs.getInt("heure"), rs.getInt("id_commande")
                });
            }
            tabseance.setModel(dtm);
        } catch (SQLException ex) {
            Logger.getLogger(SeancesE.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void afficher(int nligne) {
        tdate1.setDate((Date) tabseance.getValueAt(nligne, 1));
        theure.setText(tabseance.getValueAt(nligne, 2).toString());
        idcommande.setText(tabseance.getValueAt(nligne, 3).toString());

        try {
            stat = co.getCo().createStatement();
            rs = stat.executeQuery("SELECT c.id,c.nom,c.prenom FROM clients c,commandes_sm cm WHERE c.id= cm.id_client and cm.id=" + Integer.parseInt(tabseance.getValueAt(nligne, 3).toString()));

            if (rs.next()) {
                // Si le ResultSet contient des lignes, récupérez les données
                idclient.setText(rs.getString("id"));
                nomclient.setText(rs.getString("nom"));
                prenomclient.setText(rs.getString("prenom"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(SeancesE.class.getName()).log(Level.SEVERE, null, ex);
        }
        idcommande.setVisible(true);

        idclient.setVisible(true);
        nomclient.setVisible(true);
        prenomclient.setVisible(true);

        lidc.setVisible(true);
        lidm.setVisible(true);
        lnm.setVisible(true);
        laddm.setVisible(true);
        bsuuprimer.setVisible(true);
        pmodifier.setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmchoix = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        trecherche = new javax.swing.JTextField();
        brecherche = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        pfichec = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        bsuuprimer = new javax.swing.JButton();
        pmodifier = new javax.swing.JButton();
        bajouter = new javax.swing.JButton();
        tdate1 = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        lidc = new javax.swing.JLabel();
        idcommande = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        selectcommande = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        lnm = new javax.swing.JLabel();
        nomclient = new javax.swing.JLabel();
        jSeparator14 = new javax.swing.JSeparator();
        jPanel14 = new javax.swing.JPanel();
        laddm = new javax.swing.JLabel();
        prenomclient = new javax.swing.JLabel();
        jSeparator15 = new javax.swing.JSeparator();
        jPanel11 = new javax.swing.JPanel();
        lidm = new javax.swing.JLabel();
        idclient = new javax.swing.JLabel();
        jSeparator16 = new javax.swing.JSeparator();
        theure = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabseance = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(770, 550));
        setPreferredSize(new java.awt.Dimension(770, 550));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(250, 250, 250));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(8, 31, 92));
        jLabel1.setText("SEANCES D'ESSAYAGE");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        cmchoix.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "id ", "id_commande" }));
        cmchoix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmchoixActionPerformed(evt);
            }
        });
        jPanel1.add(cmchoix, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, -1, 30));

        jLabel6.setForeground(new java.awt.Color(0, 0, 102));
        jLabel6.setText("recherche par ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, -1, -1));

        trecherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trechercheActionPerformed(evt);
            }
        });
        trecherche.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                trechercheFocusGained(evt);
            }
        });
        jPanel1.add(trecherche, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, 120, 30));

        brecherche.setBackground(new java.awt.Color(51, 78, 172));
        brecherche.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ihm/search_2_fill (1).png"))); // NOI18N
        brecherche.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                brechercheMouseClicked(evt);
            }
        });
        brecherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brechercheActionPerformed(evt);
            }
        });
        jPanel1.add(brecherche, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, -1, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ihm/se.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 70));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 70));

        pfichec.setBackground(new java.awt.Color(208, 227, 255));
        pfichec.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pfichec.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setText("Date :");
        pfichec.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        bsuuprimer.setBackground(new java.awt.Color(51, 78, 172));
        bsuuprimer.setForeground(new java.awt.Color(255, 255, 255));
        bsuuprimer.setText("Supprimer");
        bsuuprimer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bsuuprimerMouseClicked(evt);
            }
        });
        bsuuprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsuuprimerActionPerformed(evt);
            }
        });
        pfichec.add(bsuuprimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 90, 30));

        pmodifier.setBackground(new java.awt.Color(51, 78, 172));
        pmodifier.setForeground(new java.awt.Color(255, 255, 255));
        pmodifier.setText("Modifier");
        pmodifier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pmodifierMouseClicked(evt);
            }
        });
        pmodifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pmodifierActionPerformed(evt);
            }
        });
        pfichec.add(pmodifier, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 80, 30));

        bajouter.setBackground(new java.awt.Color(51, 78, 172));
        bajouter.setForeground(new java.awt.Color(255, 255, 255));
        bajouter.setText("Ajouter");
        bajouter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bajouterMouseClicked(evt);
            }
        });
        bajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bajouterActionPerformed(evt);
            }
        });
        pfichec.add(bajouter, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 80, 30));
        pfichec.add(tdate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 210, 30));

        jButton1.setBackground(new java.awt.Color(51, 78, 172));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ihm/refresh_3_fill.png"))); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        pfichec.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, 50, 30));

        jLabel13.setText("Client : ");
        pfichec.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, -1, -1));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lidc.setText("id :");
        jPanel9.add(lidc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        idcommande.setText(".........");
        jPanel9.add(idcommande, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        pfichec.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 160, 30));

        jSeparator12.setForeground(new java.awt.Color(51, 78, 172));
        pfichec.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 160, 10));

        selectcommande.setBackground(new java.awt.Color(204, 204, 255));
        selectcommande.setForeground(new java.awt.Color(51, 78, 172));
        selectcommande.setText("+ selectionner");
        selectcommande.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        selectcommande.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selectcommandeMouseClicked(evt);
            }
        });
        pfichec.add(selectcommande, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, -1, -1));

        jLabel14.setText("Commande : ");
        pfichec.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, -1, -1));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lnm.setText("Nom :");
        jPanel10.add(lnm, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        nomclient.setText("........");
        jPanel10.add(nomclient, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        pfichec.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, 220, 30));

        jSeparator14.setForeground(new java.awt.Color(51, 78, 172));
        pfichec.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, 220, 10));

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        laddm.setText("Prenom :");
        jPanel14.add(laddm, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        prenomclient.setText("...................................");
        jPanel14.add(prenomclient, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        pfichec.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 150, 220, 30));

        jSeparator15.setForeground(new java.awt.Color(51, 78, 172));
        pfichec.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 180, 220, 10));

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lidm.setText("Id :");
        jPanel11.add(lidm, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        idclient.setText("........");
        jPanel11.add(idclient, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        pfichec.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 70, 220, 30));

        jSeparator16.setForeground(new java.awt.Color(51, 78, 172));
        pfichec.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 100, 220, 10));

        theure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                theureActionPerformed(evt);
            }
        });
        pfichec.add(theure, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 210, 30));

        jLabel3.setText("Heure :");
        pfichec.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        add(pfichec, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 740, 190));

        tabseance.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabseance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabseanceMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabseance);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 740, 260));
    }// </editor-fold>//GEN-END:initComponents

    private void bsuuprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsuuprimerActionPerformed

    }//GEN-LAST:event_bsuuprimerActionPerformed

    private void pmodifierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pmodifierMouseClicked
        if (JOptionPane.showConfirmDialog(this, "voullez vous vraiment modifier ?", "modification",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            boolean vide = false;

// Récupérer les données du formulaire
            Date date = tdate1.getDate();
            String tt = theure.getText();
            String vidc = idcommande.getText();

            if (date == null || tt.isEmpty() || vidc.isEmpty()) {
                vide = true;
            }

            if (!vide) {
                // Vérifier si ttotale ne contient que des chiffres
                Pattern pattern = Pattern.compile("\\d+");
                Matcher matcherT = pattern.matcher(tt);

                if (!matcherT.matches()) {
                    JOptionPane.showMessageDialog(null, "La saisie de l'heure n'est pas valide");
                } else {
                    try {
                        ps = co.getCo().prepareStatement("UPDATE seances_dessayage SET date=?,"
                                + "heure=?,id_commande=? WHERE id=?");
                        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                        ps.setString(1, sdf.format(tdate1.getDate()));
                        ps.setInt(2, Integer.parseInt(theure.getText()));
                        ps.setInt(3, Integer.parseInt(idcommande.getText()));
                        ps.setInt(4, Integer.parseInt(tabseance.getValueAt(tabseance.getSelectedRow(), 0) + ""));
                        ps.execute();
                        JOptionPane.showMessageDialog(this, "Modification faite avec succes");
                        actualiser();
                        reinitialiser();
                    } catch (SQLException ex) {
                        Logger.getLogger(SeancesE.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            } else {
                JOptionPane.showMessageDialog(null, "Vous devez remplir tous les champs");
            }
        }

    }//GEN-LAST:event_pmodifierMouseClicked

    private void pmodifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pmodifierActionPerformed


    }//GEN-LAST:event_pmodifierActionPerformed

    private void bajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bajouterActionPerformed

    }//GEN-LAST:event_bajouterActionPerformed

    private void tabseanceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabseanceMouseClicked
        afficher(tabseance.getSelectedRow());
    }//GEN-LAST:event_tabseanceMouseClicked

    private void cmchoixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmchoixActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmchoixActionPerformed

    private void trechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trechercheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_trechercheActionPerformed

    private void trechercheFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_trechercheFocusGained
        reinitialiser();
        actualiser();
    }//GEN-LAST:event_trechercheFocusGained

    private void brechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brechercheActionPerformed

    }//GEN-LAST:event_brechercheActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    }//GEN-LAST:event_jButton1ActionPerformed

    private void selectcommandeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectcommandeMouseClicked
        lcm.setVisible(true);
        lcm.actualiser();
    }//GEN-LAST:event_selectcommandeMouseClicked

    private void bajouterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bajouterMouseClicked

        boolean vide = false;

// Récupérer les données du formulaire
        Date date = tdate1.getDate();
        String tt = theure.getText();
        String vidc = idcommande.getText();

        if (date == null || tt.isEmpty() || vidc.isEmpty()) {
            vide = true;
        }

        if (!vide) {
            // Vérifier si ttotale ne contient que des chiffres
            Pattern pattern = Pattern.compile("\\d+");
            Matcher matcherT = pattern.matcher(tt);

            if (!matcherT.matches()) {
                JOptionPane.showMessageDialog(null, "La saisie de l'heure n'est pas valide");
            } else {
                try {
                    ps = co.getCo().prepareStatement("INSERT INTO seances_dessayage (date,heure,id_commande) VALUES(?,?,?)");

                    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                    ps.setString(1, sdf.format(tdate1.getDate()));
                    ps.setInt(2, Integer.parseInt(theure.getText()));
                    ps.setInt(3, Integer.parseInt(idcommande.getText()));
                    ps.execute();
                    JOptionPane.showMessageDialog(null, "seance enregistrée");
                    reinitialiser();
                    actualiser();
                } catch (SQLException ex) {
                    Logger.getLogger(SeancesE.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Vous devez remplir tous les champs");
        }
    }//GEN-LAST:event_bajouterMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        reinitialiser();
        actualiser();
    }//GEN-LAST:event_jButton1MouseClicked

    private void bsuuprimerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bsuuprimerMouseClicked
        if (JOptionPane.showConfirmDialog(this, "voulez vous vraiment supprimer ?", "suppression", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            try {
                stat = co.getCo().createStatement();
                stat.executeUpdate("DELETE FROM seances_dessayage WHERE id='" + tabseance.getValueAt(tabseance.getSelectedRow(), 0) + "'");
                JOptionPane.showMessageDialog(this, "suppression faite avec succes");
                actualiser();

                reinitialiser();
            } catch (SQLException ex) {
                Logger.getLogger(SeancesE.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_bsuuprimerMouseClicked

    private void brechercheMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brechercheMouseClicked
        String s;
        s = cmchoix.getSelectedItem().toString();
        try {

            ps = co.getCo().prepareStatement("SELECT * FROM seances_dessayage WHERE " + s + "=?");
            ps.setInt(1, Integer.parseInt(trecherche.getText()));

            rs = ps.executeQuery();
            dtm.setRowCount(0);
            while (rs.next()) {
                dtm.addRow(new Object[]{rs.getInt("id"), rs.getDate("date"), rs.getInt("heure"), rs.getInt("id_commande")});

            }
            tabseance.setModel(dtm);
            if (dtm.getRowCount() != 0) {
                afficher(0);
            } else {
                actualiser();
                JOptionPane.showMessageDialog(this, "seance n'existe pas");
            }

        } catch (SQLException ex) {
            Logger.getLogger(SeancesE.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_brechercheMouseClicked

    private void theureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_theureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_theureActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton bajouter;
    private javax.swing.JButton brecherche;
    private javax.swing.JButton bsuuprimer;
    private javax.swing.JComboBox<String> cmchoix;
    public static javax.swing.JLabel idclient;
    public static javax.swing.JLabel idcommande;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    public static javax.swing.JLabel laddm;
    public static javax.swing.JLabel lidc;
    public static javax.swing.JLabel lidm;
    public static javax.swing.JLabel lnm;
    public static javax.swing.JLabel nomclient;
    private javax.swing.JPanel pfichec;
    private javax.swing.JButton pmodifier;
    public static javax.swing.JLabel prenomclient;
    private javax.swing.JLabel selectcommande;
    private javax.swing.JTable tabseance;
    public com.toedter.calendar.JDateChooser tdate1;
    private javax.swing.JTextField theure;
    private javax.swing.JTextField trecherche;
    // End of variables declaration//GEN-END:variables
}
